### ISSUE TITLE
[FEAT] Detect Fixed / Hug / Fill dimensions

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#101]
Currently the editor will display decimal values for calculated values. This is not particularly useful for showing how width and height are set up for an element. 

<img width="376" alt="Screenshot 2024-08-01 at 4 34 17 PM" src="https://github.com/user-attachments/assets/ff986334-1f50-4176-a036-19b68c5faa00">
<img width="914" alt="Screenshot 2024-08-01 at 4 34 33 PM" src="https://github.com/user-attachments/assets/ee9bf7b5-a9f6-41c7-b3a0-32aaa6724efd">
<img width="360" alt="Screenshot 2024-08-01 at 4 34 46 PM" src="https://github.com/user-attachments/assets/dfa47968-bd56-4755-89ce-3930f9f5489d">

Ideally, we're able to detect how those dimensions are calculated and displayed to the user. 

This also ties in with https://github.com/onlook-dev/studio/issues/97

**Comment by Kitenite** [comment]
^ Partial fix in better styles. 

Still need to determine styles when they don't exist to be hug/fill/etc based on display type.
