### ISSUE TITLE
[FEAT] Resizable and Draggable Handles to Divs

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#103]
#### Describe the feature
Have handles on the display rectangles to be able to 
1. resize
2. change corner radius

Right now, the rectangles are implemented as non-touchable svgs on the overlay layer. But it would be better to update these to React components that have logic and handles. Very open to interpretation.

https://github.com/onlook-dev/studio/blob/main/app/src/lib/editor/engine/overlay/rect.ts
https://github.com/onlook-dev/studio/blob/main/app/src/lib/editor/engine/overlay/index.ts

<img width="345" alt="Screenshot 2024-08-16 at 9 39 25 AM" src="https://github.com/user-attachments/assets/0be8ad00-3a14-428e-8fe9-836864545b09">

#### Requirement clarification:
https://www.loom.com/share/2083559006b64a14b71b9084f164e237?sid=cdcf7a18-f68e-4391-9c42-ff250ca228e1

#### Implementation suggestion:
I would suggest splitting this task into 2 PRs:
1. Re-implement the Rect elements in React components instead of custom HTML elements
2. Implement the controls in the new Rect elements

Reasoning: 
For legacy reason, the overlay rects are implemented as HTML element. This is because they used to be inserted into the DOM directly. However, this is not extensible because we want these rects to fit some logic on them.

**Comment by SkyC0der** [comment]
Can I take this up?

**Comment by Kitenite** [comment]
@SkyC0der for sure! I assigned it to you

**Comment by kartik-raj7** [comment]
Can you assign me this issue. I would like to work on it.

**Comment by Kitenite** [comment]
Great will do!

@SkyC0der since you are working on https://github.com/onlook-dev/onlook/issues/174 , I'll let @kartik-raj7 start on this. Hope that's ok!

**Comment by SkyC0der** [comment]
Yeah, It's fine!

**Comment by Kitenite** [comment]
I updated the description with a Loom walking through the requirements and implementation suggestion. @kartik-raj7

**Comment by kartik-raj7** [comment]
> I updated the description with a Loom walking through the requirements and implementation suggestion. @kartik-raj7

Ya Just saw the video its clear now what needs to be done thanks
