### ISSUE TITLE
[FEAT] Better docs page

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#105]
#### Describe the feature
The docs + onboarding steps should be easier. There's a React app under [docs](https://github.com/onlook-dev/onlook/tree/main/docs) that should be the official docs site soon.

There's a folder called [docs](https://github.com/onlook-dev/onlook/tree/main/docs) in the repo that is a React + Nextjs + TailwindCSS app with routing set up. 

* We should create template pages similar to [Supabase's docs](https://mintlify.com/docs/quickstart) or [Mintlify's docs](https://mintlify.com/docs/quickstart) so that we can add content later.
* Should continue using ShadCN's UI library.

Once this is done, we'll hook up some automatic hosting to it.

**Comment by Kitenite** [comment]
@Vaibhav4228 sounds great!
There's a folder called [docs](https://github.com/onlook-dev/onlook/tree/main/docs) in the repo that is a react next js app with routing set up. Would you want to set up some template pages similar to [Supabase's docs](https://mintlify.com/docs/quickstart) or [Mintlify's docs](https://mintlify.com/docs/quickstart) so that we can add content later that would be awesome!

I would prefer if we continue using ShadCN's UI library as well. Does this help? 

@drfarrell please add any details you see missing

**Comment by ray-wienand** [comment]
@Kitenite I can assist as well.
I would like to reach out in assisting you. I believe there are several areas where I can offer valuable support.

**Comment by Kitenite** [comment]
@ray-wienand for sure, go ahead!

**Comment by Kitenite** [comment]
@Vaibhav4228 let me know if you'd still also like to work on this issue, I can create a separate docs-related issue for you :)

**Comment by ray-wienand** [comment]
> @Vaibhav4228 let me know if you'd still also like to work on this issue, I can create a separate docs-related issue for you :)

@Kitenite I found Onlook thanks to @Vaibhav4228 doing a collaboration shoutout in a mutual Discord server. More than happy to have him involved.

**Comment by Kitenite** [comment]
Awesome, I'll add you both to the issue 
@Vaibhav4228  @ray-wienand

**Comment by Vaibhav4228** [comment]
@ray-wienand  you can start I can join you after some times because I am working on different project right now.

**Comment by Kitenite** [comment]
Hey @ray-wienand @Vaibhav4228 ,
Just checking in to see how this is going. Do you need any support from my side?

**Comment by ray-wienand** [comment]
Getting there @Kitenite. Should have 1st draft for you to look at on the weekend.

**Comment by Kitenite** [comment]
Closing since docs are moved to https://github.com/onlook-dev/docs
