### ISSUE TITLE
[Bug] Error in adding in a style class + detecting the class is applied

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#118]
There’s a disconnect between what is shown on the screen and what is “read” by the UI. I think it’s because there was a class that was added in incorrectly to the div by Onlook. 

As shown in the screenshot, you can see that Onlook's UI says there is a blue border, but there isn't a blue border on the actual element. My guess is that it's because the class is added outside of the other classes. 

<img width="644" alt="image" src="https://github.com/user-attachments/assets/c60fd8ed-8299-43e1-904a-513b5ddd7bd0">

**Comment by Kitenite** [comment]
Seems to be because there's not border width. The width should show up beneath in this case.

**Comment by Kitenite** [comment]
On further look, after writing to code, the older value is sticking for some reason.

**Comment by Kitenite** [comment]
@drfarrell seems like there's 2 things happening:
1. There might be a border being shown but it's under the selection rectangle which is red. 
2. There might be a border color but no border width. In this case, we should at least show the border width input.

**Comment by drfarrell** [comment]
> There seems to be a border color set but no border width. This seems to be correct but not expected. What should the expect behavior here @drfarrell ? If there is a color, we display the dropdown?

Is it possible to read in the parent setting for the border width and display that? I think we probably should display the dropdown, it seems like the width is what's missing

**Comment by Kitenite** [comment]
So seems like there's actually default border colors applied to those elements but no width. There are 2 solutions:
1. If there's no border width, show an empty border color and no dropdown
2. If there's a border color, display the whole dropdown

For 2, we will likely see many 0px border width with a color. @drfarrell thoughts?

**Comment by drfarrell** [comment]
> So seems like there's actually default border colors applied to those elements but no width. There are 2 solutions:
> 
> 1. If there's no border width (0px), even if there is a color, show an empty border color and no dropdown
> 
> <img alt="Screenshot 2024-09-04 at 4 25 46 PM" width="229" src="https://private-user-images.githubusercontent.com/31864905/364537208-48f5c86e-16f6-489d-82be-aca6f3a920cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0ODI2NzEsIm5iZiI6MTcyNTQ4MjM3MSwicGF0aCI6Ii8zMTg2NDkwNS8zNjQ1MzcyMDgtNDhmNWM4NmUtMTZmNi00ODlkLTgyYmUtYWNhNmYzYTkyMGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDIwMzkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOGIzZmE1ZDRjMjc5NzQ3YzhmN2QwMzgwZjc5MWRlYWE3ODYxZGE0MTlmNmM3OWRjNDc1MTc3ZGMyZjc1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rEfOEeq6bZuSRj7Ru8w6BVxVVl22QYUMPVKBAHMN9pA">
> 2. If there's a border color, display the whole dropdown, even if there's no border width
> 
> <img alt="Screenshot 2024-09-04 at 4 27 11 PM" width="231" src="https://private-user-images.githubusercontent.com/31864905/364537460-6a8a4775-4e6b-44e5-a051-f5feb20ed728.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0ODI2NzEsIm5iZiI6MTcyNTQ4MjM3MSwicGF0aCI6Ii8zMTg2NDkwNS8zNjQ1Mzc0NjAtNmE4YTQ3NzUtNGU2Yi00NGU1LWEwNTEtZjVmZWIyMGVkNzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDIwMzkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZDAzMDA4OGZiYmRmMWFhZjQxN2I2YTU2MjJjYTFiNTVkMDVjMTAzMWRmMDQ1OGQxYzAwZDk3NDgxMjEzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DhY17dDeEWrvYN5BSVuA9hsa6AZXt1Sbn5w2ZNMsmVU">
> For 2, we will likely see many 0px border width with a color. @drfarrell thoughts?

It seems like 2 is the way to go. Perhaps it's just for ShadCN that this happens, but it feels more accurate to reality.
