### ISSUE TITLE
[FEAT] Detect when a project does not have plugin added and notify user

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#137]
#### Describe the feature
When our plugin is added, most DOM elements should have the `data-onlook-id` attribute. We can scan the DOM tree for this attribute or just pick it up as we parse the DOM tree. If none is found, we should let the user know and prompt them to add the plugin. 

@drfarrell thoughts on how this should look on the user end? I would think an error indicator on the code side or on the browser page should work.

**Comment by drfarrell** [comment]
I like both approaches – something in the editor and perhaps a persistent toast in the corner OR as a modal on the front page. 

If it's disruptive as a large modal though, it'll need some good documentation though, so definitely something to consider.

**Comment by Kitenite** [comment]
I think a persistent icon on the code-related modules would do
