### ISSUE TITLE
[Bug] Need minimum values for numeric style inputs that can't be negative

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#147]
- [ ] Corner / Border radius can't be negative, and shouldn't go lower than 0
- [ ] Padding can't be negative, and shouldn't go lower than 0
- [ ] Width can't be negative
- [ ] Height can't be negative
- [ ] Font size can't be negative
- [ ] Opacity can't be negative

HOWEVER, 
- GAP in flexbox can be negative
- Letter can be negative

**Comment by drfarrell** [comment]
Encountered this issue today with an insert element.

**Comment by kartik-raj7** [comment]
Hey @drfarrell  @Kitenite  Can I take on this issue !

**Comment by cleobnvntra** [comment]
Hello @drfarrell. I noticed that this current issue still exist in the latest version and no PRs has been made for it. I was wondering if I can try working on it and submit a PR if one hasn't been made when I finish the task?

**Comment by Kitenite** [comment]
Hey @cleobnvntra ,
This was actually open. Go for it!

**Comment by cleobnvntra** [comment]
Thank you @Kitenite !

I've been looking at the code and there's two ways I think we can deal with this, so I wanted to ask what is the preferred solution:

1. If a user inputs a negative number, just default the input back to 0px (or any other non-negative default value if not 0).

2. Display a toast showing that the input is invalid with a simple message saying what the acceptable input is.

Can definitely change the message to your liking, but here's a sample:

![image](https://github.com/user-attachments/assets/a362b0c4-c8c7-4c7f-92aa-4caea9522a3e)

Let me know what you think!

**Comment by Kitenite** [comment]
Tagging @drfarrell for input. I think the toast works. 

@cleobnvntra  You've probably seen this but we actually have min/max implemented in the style interface which can be added to any of the class here. We just haven't enforced the value :)
https://github.com/onlook-dev/onlook/blob/eb697af01c05970b3706a25fb1568a975d46b76b/app/src/lib/editor/styles/group.ts#L17
