### ISSUE TITLE
[Bug] Change count includes undoing issues

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#149]
If a user adjusts something and then adjusts it back to the original value, it still is counted as a change. 

<img width="146" alt="image" src="https://github.com/user-attachments/assets/57c706a8-cadd-4676-9512-9d53fc2eb06c">

The expected behavior is to return to the original count of changes as if the user didn't make the changes in the first place.

**Comment by Kitenite** [comment]
> The expected behavior is to return to the original count of changes as if the user didn't make the changes in the first place.
I don't believe that this is correct behavior. We should be expecting every action to be tracked as an action. If a user oscillates between 2 values, it should be tracked and undoable. 

Figma, Framer exhibit similar behavior and I don't think we should have extra logic to prevent this case.
