### ISSUE TITLE
[FEAT] Drag and Drop elements on the canvas and in the layers panel

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#157]
A core feature of the editor is the ability to visually rearrange elements on the page itself. 

There are two surfaces that drag and drop can happen on:

1. The Canvas
2. The Layers Panel

For the Canvas, it is expected that layers within a parent layer can be re-sorted within their parent layer. More complex functionality would be to allow the layer to be placed in a different parent layer, but that can be implemented after layers can be re-sorted in their main layer. 

For the Layers Panel, it is expected that layers can be resorted within their parent div. More complex functionality would allow users to re-sort layers to other layers in the stack. As a user drags the layer, it'd be great to have a distinct line appear where the layer will be inserted, similar to the gif below.

![Export-1723660731162](https://github.com/user-attachments/assets/aaaaee72-e9cf-4f35-91ec-cdcd325e947d)

In both cases, when a layer is dragged to a new spot, the pre-existing layer would nicely animate to the new location in the array. I believe we used Framer Motion for this in the past, but it could probably be achieved with CSS.

**Comment by Kitenite** [comment]
This was implemented on the canvas, not on the layers. We should open a separate issue for the layer panel.

**Comment by Kitenite** [comment]
https://github.com/onlook-dev/onlook/issues/263
