### ISSUE TITLE
[FEAT] Add unit test coverage tracking

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#169]
#### Describe the feature
We have a few unit tests with bun but need a better idea of our test coverage. 

We currently use bun-test for our unit test. Seems like Bun has some good options for test coverage tracking. Could you add some automatic test coverage options (even just a command in our package.json) or configuration? Up to your research on what is the best, most sustainable approach. 

The end goal is to have an easy way to see our test coverage so that we can improve. 

https://bun.sh/docs/test/coverage

**Comment by vr-varad** [comment]
@Kitenite I would like to work on this issue!! would u mind giving some more info regarding the issue

**Comment by Kitenite** [comment]
Hey @vr-varad ,
Great! I will assign this to you. We currently use bun-test for our unit test. Seems like Bun has some good options for test coverage tracking. Could you add some automatic test coverage options (even just a command in our package.json) or configuration? Up to your research on what is the best, most sustainable approach. 

The end goal is to have an easy way to see our test coverage so that we can improve. 

https://bun.sh/docs/test/coverage

**Comment by Kitenite** [comment]
@vr-varad how's it going? Do you need any support on this?

**Comment by vr-varad** [comment]
Almost Done, being in college was stuck with exams will make a pr by tomorrow @Kitenite hope u understand
