### ISSUE TITLE
[FEAT] Insert element

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#172]
Ability for a user to insert a div or a text box onto the page. 

Requirements
- [x] The user should be able to draw the rough size of the element on the canvas using their cursor
- [x] The width and height of the element should match the size that the user manually draws.
- [x] The user should be able to apply styles to their drawn element
- [x] The element should be writeable to the codebase 
- [ ] The element should not conflict with inline elements as it is drawn onto the page and/or written to code

**Comment by Kitenite** [comment]
Reopening for 1 more edge case detailed in https://github.com/onlook-dev/onlook/pull/168
