### ISSUE TITLE
[FEAT] Make the component outline purple when selected on a canvas

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#174]
The default canvas selection outline for a component is red. Make it purple when it's selected to indicate that the selected element is a component.

**Comment by SkyC0der** [comment]
Is there a particular hex code you would want or any shade of purple is fine?

**Comment by SkyC0der** [comment]
Kindly review my PR #181

**Comment by drfarrell** [comment]
@SkyC0der it should be the tailwind class purple-500 so it's on-brand with our styles. 

I'm not sure if it's rendered as an .svg if it should be border-purple-500 or bg-purple-500 but purple-500 is the correct class. You'll have to test to see which one actually covers the color.
