### ISSUE TITLE
[FEAT] Close side panels

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#180]
Add in the functionality for a user to close the left or right side panels.

Ideally the panels are animated after the user clicks a side button

<img width="750" alt="Screenshot 2024-08-19 at 4 28 52 PM" src="https://github.com/user-attachments/assets/40d87fda-5f20-44cf-b6b0-fdbcf7705f4f">

The buttons should still remain exposed for a user to click on to re-open the page.
<img width="474" alt="image" src="https://github.com/user-attachments/assets/0168a327-b0ec-463c-a980-9450e50e2c5d">

**Comment by kartik-raj7** [comment]
Hey can you assign me this issue

**Comment by drfarrell** [comment]
Go for it!
