### ISSUE TITLE
[Bug] Improve visuals of input backgrounds to better-match designs

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#194]
Make the background of inputs slightly opaque so that the inputs also appear to have frosted-glass backgrounds.

This is very very easy – implement the code as highlighted to the right inputs.

![image](https://github.com/user-attachments/assets/ed3b10a4-7a11-458c-aff9-a4ad863a58a6)

**Comment by drfarrell** [comment]
Go for it!

**Comment by kartik-raj7** [comment]
Thank you so much, I will let you know if I have any doubts.

**Comment by Kitenite** [comment]
This was fast, awesome work @kartik-raj7 !
