### ISSUE TITLE
[FEAT] Saving project state/settings

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#197]
#### Describe the feature
This will be part of a larger initiative to add persistence into the project. Project state should be savable and restored on start. Some initial data to retain:

1. URL of frames
2. Current editing state
3. Position + scale of frames
4. Dimensions of frames

My proposal: 
Have a serializable object representing the current frame. Save state to the object over time and save to disk when idle. Then restore on reload.

**Comment by bkrmendy** [comment]
This could also be tied into the undo/redo system so that the state is serialized after an action has been dispatched

**Comment by Kitenite** [comment]
I'm opting not to store history for now as it needs to be reproducable which can have quite a few edge cases. We'll be happy with saving  for now 

1. URL of frames
2. Position + scale of canvas
3. Dimensions of frames
