### ISSUE TITLE
[Bug] Onlook Studio doesn't auto update like it used to

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#204]
The notification that it will install the latest version persists and it doesn't seem to install on the next reboot of the app

![image](https://github.com/user-attachments/assets/21e59f4c-b11c-4045-b4ee-294b1c56a730)

**Comment by Kitenite** [comment]
![image](https://github.com/user-attachments/assets/1f74ca9f-1e22-494f-bc95-873520bac782)

**Comment by Kitenite** [comment]
Close for now since there's no reproduction and it's working regularly again. Please feel free to reopen.

**Comment by Kitenite** [comment]
Reopening for an encounter. A suggested solution is to have a manual update button. Check for update.

**Comment by Kitenite** [comment]
It may be very slow because of the way github handles artifacts. It may take a few days for an update to apply. There are a few fixes here.

1. Use a CDN on top of Github Releases
2. Delete old releases (this is reported to speed up)

I like the CDN method, will look more into this.
