### ISSUE TITLE
[Documentation errors] just a couple

### ISSUE THREAD

**Issue by ScubyG** [onlook-dev/onlook#218]
This is a fantastic project having just found it searching for something like this, whilst I have been reading the docs and installing Onlook, I noticed a few errors in the documentation:

`160# See the [CONTRIBUTING.md](readme/CONTRIBUTING.md) for instructions and code of conduct.`
**Change**
`See the \[CONTRIBUTING.md](CONTRIBUTING.md) for instructions and code of conduct or move file to readme folder.`

`82# cd studio/app`
**Change**
`cd /onlook/app`

I can PR this and any others I might find as I go through all of the docs or wait until I have looked through all of them and send one.

Thanks for the great work and I look forward to testing this out

**Comment by Kitenite** [comment]
Hey @ScubyG , 
Nice catch! The docs haven't caught up with all the latest changes. A PR would be awesome as you look through the docs with fresh eyes. Otherwise I'll make a note to update the docs as well :)

**Comment by ScubyG** [comment]
I am more than happy to help out

**Comment by Kitenite** [comment]
Closing since you PR'ed. Thanks @ScubyG !
