### ISSUE TITLE
[Bug] Layers lazy loading is a bad experience

### ISSUE THREAD

**Issue by TroyRobinson** [onlook-dev/onlook#223]
#### Describe the bug

Some layers do not load in the left panel until you click on them (based on the demo site)

P.S. Awesome work so far! All the best parts from Codux, Figma, Repaint, Webflow, and Utopia!

**Comment by Kitenite** [comment]
@TroyRobinson , we're currently lazy-loading layers for performance reasons but will do a layer overhaul to address this. I renamed the issue for better tracking

**Comment by Kitenite** [comment]
Done, thanks for opening the issue @TroyRobinson !
