### ISSUE TITLE
[Bug] Margin error

### ISSUE THREAD

**Issue by TroyRobinson** [onlook-dev/onlook#225]
#### Describe the bug

Sometimes a margin of an element will be listed as 0 and yet it is actually a large number. Test by opening the demo, clicking the "track order" combination button in the top right. Notice the margin in 0. If you change it to zero again, the space collapses.

P.S. Awesome work so far!

**Comment by Kitenite** [comment]
Seems we are not handling `margin-left: auto` well in this case

**Comment by Kitenite** [comment]
Fixed in https://github.com/onlook-dev/onlook/pull/296 !
