### ISSUE TITLE
[FEAT]  Drag & drop, Group & ungroup, Componentize

### ISSUE THREAD

**Issue by TroyRobinson** [onlook-dev/onlook#226]
#### Describe the feature

Probably top of your roadmap although just in case not, would be very useful to be able to drag and drop elements, group them together, and turn them into components. (like Figma). Thanks so much!

**Comment by Kitenite** [comment]
> drag and drop elements
@TroyRobinson this is coming out in a few days! https://github.com/onlook-dev/onlook/issues/157

> group them together, and turn them into components.

I agree with this. For grouping, we have plans to allow you to wrap a div around elements. And for new component we'd do a refactor in code. 

@drfarrell @Eejya do we have an issue for these yet?

**Comment by drfarrell** [comment]
We have grouping in #173 that is with multi-select. Perhaps we use this ticket that @TroyRobinson just made for making Components from scratch, because we have DnD in #157 like you said, Grouping in #173, and while we do have #114 for inserting components, we don't have a Create new component flow.

**Comment by Kitenite** [comment]
New issue for grouping components https://github.com/onlook-dev/onlook/issues/264

**Comment by Kitenite** [comment]
Drag and drop is solved in https://github.com/onlook-dev/onlook/issues/157

**Comment by Kitenite** [comment]
New issue for editing / creating components https://github.com/onlook-dev/onlook/issues/265

**Comment by Kitenite** [comment]
Closing this for duplicate
