### ISSUE TITLE
[FEAT] Edit source component

### ISSUE THREAD

**Issue by TroyRobinson** [onlook-dev/onlook#227]
#### Describe the feature

Option in the right sidebar to edit the styles of the source component instead of just that instance. Changes would immediately be reflected across all instances of that component. (like editing the source component in Figma)

**Comment by Kitenite** [comment]
We're actually able to do it now in the publish code panel. We deferring this for an actual UI flow (also similar to Figma)  @drfarrell 

Ideally, when opting to edit component, all the reused-elements on the page would be updated as well.

**Comment by Kitenite** [comment]
This is now implemented
