### ISSUE TITLE
[FEAT] Visual indicator for when frame is focused

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#235]
#### Describe the feature
Currently, the webviewtag can steal the focus on interact mode. This changes the way hotkeys and zoom work until focus is taken back. This is intended behavior but we need an visual indicator that this is happening. 

May want different design for design mode focus vs interact mode focus?

**Comment by drfarrell** [comment]
I mocked this up. The teal may conflict with our red for the design mode, but I think I'd like to see it implemented and make a gametime call on what feels best. 

![image](https://github.com/user-attachments/assets/78c58c27-940c-40d8-9b63-a6b28387b6ce)
