### ISSUE TITLE
[FEAT] pnpm support in CLI

### ISSUE THREAD

**Issue by lusqua** [onlook-dev/onlook#243]
#### Describe the feature

I would like Onlook to support pnpm as an alternative package manager to npm and yarn. pnpm is gaining popularity due to its efficient disk space usage and faster installation times, which are critical for larger projects and CI/CD pipelines. Adding support for pnpm will allow developers who prefer or require pnpm to seamlessly integrate Onlook into their workflows.

#### Expected Behavior:

- Onlook should be able to detect and use pnpm when it is the preferred package manager in a project.
- When running pnpx onlook, the tool should be capable of using pnpm for package installations and related tasks.

#### Use cases:

- Developers working on large projects who prefer pnpm for its performance benefits.
- Teams using pnpm in CI/CD environments to reduce build times and storage costs.

**Comment by Kitenite** [comment]
Thanks for the issue @lusqua I can see this being useful in the CLI for setup! We'll get this prioritized.

**Comment by drfarrell** [comment]
Putting a comment to +1 from Jake's conversation today
