### ISSUE TITLE
[Bug] When dragging an element, preserve it's size 

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#245]
When a user drags an element, the element dimensions expand to fill the parent layer or start to act weird. The expected behavior would be for the preview pic to maintain the same width while being dragged. 

You can see how the div (whose width is set to "full") expands well beyond what you'd expect (it was originally like 100px wide)
<img width="986" alt="Screenshot 2024-08-29 at 4 11 18 PM" src="https://github.com/user-attachments/assets/6169c9b7-da30-4152-9ec9-396eb46416de">

**Comment by Kitenite** [comment]
Yeah we should be mocking out the width and height to their rendered value when dragged.
