### ISSUE TITLE
[Bug] Border controls missing if a child div inherits a border color class from a parent

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#250]
It seems like if a border is applied to a parent class, the child shows the border color (in this case perhaps it's an issue here #118) @Kitenite  for comment

<img width="968" alt="image" src="https://github.com/user-attachments/assets/3496faaa-f2cc-4864-8634-e17dd170cde4">

<img width="932" alt="image" src="https://github.com/user-attachments/assets/63432f04-b8b4-47b3-88a1-7328f83fa779">

**Comment by Kitenite** [comment]
Border color is [not an inherited property ](https://developer.mozilla.org/en-US/docs/Web/CSS/border-color#formal_definition)and should be treated as such. This is likely a bug and likey related to https://github.com/onlook-dev/onlook/issues/118

**Comment by Kitenite** [comment]
Closing as this is fixed as part of editor enhancements
