### ISSUE TITLE
[FEAT] Layer colors for newly added elements

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#252]
Much like how we have purple styles for the UI if something is a component, #174 Let's make blue styles for a div or element that is newly added and not written to code. 

To do this, I'd recommend following the code implemented here: #181 for how the colors of the layers panel change on hover to various hues of purple if the element is a component. Add in logic for if the element is new and use the same color scheme as the purple (ex. bg-purple-500) but with blue (ex. bg-blue-500). 

Same colors, same logic for hovers, just on new elements and in blue.

**Comment by orunto** [comment]
Hey @drfarrell may I be assigned to this?

**Comment by Kitenite** [comment]
Go ahead @orunto !

**Comment by orunto** [comment]
Thank you.

**Comment by drfarrell** [comment]
This issue is no-longer needed, as elements are instantly written to the page. Thanks!
