### ISSUE TITLE
[FEAT] Animate the mode selector bar at the top of the page

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#255]
Animate this bar at the top so when a user clicks on the other mode, it slides over to that mode. 

You can likely implement with Framer Motion. Ease in-out curve – NOT a spring curve please. 

<img width="232" alt="image" src="https://github.com/user-attachments/assets/2caff73b-4d14-4446-b25d-16ee1d797e16">

**Comment by kash-eesh** [comment]
hey, can I take up this issue?

**Comment by Kitenite** [comment]
@kash-eesh go for it!
