### ISSUE TITLE
[Bug] Invalid prop `data-onlook-id` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.

### ISSUE THREAD

**Issue by nathanredblur** [onlook-dev/onlook#262]
#### Describe the bug
on run this in a nextjs project I get this errors
```
Warning: Invalid prop `data-onlook-id` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
```

also, the only visible layer is body and publish code not detect any change.
![CleanShot 2024-08-31 at 11 03 07](https://github.com/user-attachments/assets/02c5763f-ebfb-4e4c-a431-6373a98306e2)
![CleanShot 2024-08-31 at 11 03 22](https://github.com/user-attachments/assets/b7d93493-ac18-46d3-a162-8199a9f85a30)

My stack is:
"next": "^14.0.1", (page mode)
"react": "^18.3.0",
"tailwindcss": "^3.4.10",
"@onlook/nextjs": "^2.1.0",

**Comment by Kitenite** [comment]
Seems like `data-onlook-id` should not be writing to React Fragment. 
May be unrelated but looks like code understanding is not being picked up in this case.

**Comment by Kitenite** [comment]
@nathanredblur ,

Looking into this now, it seems like the code detection is working. It may need a refresh with CMD+R. The warning should not be breaking as fragments are stripped anyway. 

Did you make any change and it did not show up?
