### ISSUE TITLE
[FEAT] Allow grouping components

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#264]
#### Describe the feature
Related to https://github.com/onlook-dev/onlook/issues/226 , we should be able to group components together (inserting a div on the top grouping). 

Is dependent on https://github.com/onlook-dev/onlook/issues/173 for selecting multiple components.

Should be able to be done from right-click menu and hotkey

**Comment by drfarrell** [comment]
@Kitenite made this so closing the issue.
