### ISSUE TITLE
[Bug] Stray file with local paths

### ISSUE THREAD

**Issue by szepeviktor** [onlook-dev/onlook#269]
#### Describe the bug

# 🚨 

https://github.com/onlook-dev/onlook/blob/main/app/vite.config.ts.timestamp-1724434945065-9ba7ea614a309.mjs

**Comment by szepeviktor** [comment]
Another file, seems to be generated and minified.

https://github.com/onlook-dev/onlook/blob/main/app/electron/preload/webview/changes/csstree.esm.js

**Comment by Kitenite** [comment]
> Another file, seems to be generated and minified.
> 
> https://github.com/onlook-dev/onlook/blob/main/app/electron/preload/webview/changes/csstree.esm.js
> 
> maybe `bun install css-tree`

This one is inline dependency for the preload script. It is intended. 

>  https://github.com/onlook-dev/onlook/blob/main/app/vite.config.ts.timestamp-1724434945065-9ba7ea614a309.mjs

This vite timestamp file, however, can be gitignored. I have a PR for that. Thanks @szepeviktor !

**Comment by Kitenite** [comment]
Solved as a gitignore update in https://github.com/onlook-dev/onlook/pull/267

**Comment by szepeviktor** [comment]
@Kitenite app/vite.config.ts.timestamp-1724434945065-9ba7ea614a309.mjs is still not deleted.

**Comment by Kitenite** [comment]
Right, deleted!
