### ISSUE TITLE
[Bug] Improve alignment of top bar labels and show/hide button

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#273]
The labels of the various categories are misaligned – they appear to be too high up (or there's extra margin below them.

Here are my recommended corrections.

![image](https://github.com/user-attachments/assets/d6912d4a-8a95-4c23-8517-ff2366803f41)

**Comment by drfarrell** [comment]
Also, the other labels besides the active one (Components, in this example) should have text-hover as a style applied on hover

<img width="233" alt="image" src="https://github.com/user-attachments/assets/e83a4bb6-272a-40dc-bc4d-ac0450a0eab6">

**Comment by Sai-Manikanta-Andey** [comment]
Hey I would like to work on it .Could you assign me if possible !

**Comment by Kitenite** [comment]
You got it @Sai-Manikanta-Andey !

**Comment by Sai-Manikanta-Andey** [comment]
Hi @Kitenite ,

Before creating a pull request, I wanted to check with you if this solution looks good. I've attached a short video that demonstrates the issue and my fix.



https://github.com/user-attachments/assets/b4f00a51-a8cf-44dc-b3e4-1b2c466f2b80



Please let me know if this approach works, or if you have any suggestions before I proceed with the PR.

Thank you!
