### ISSUE TITLE
[FEAT] Tooltip for concatenated layer name text

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#274]
Create a tooltip in the sidepanel for cut-off layer name text if the width of the layer panel doesn't allow you to read the whole layer label.

The tooltip instantly pops up on hover for the layer but only if the text is cut off. No tooltip for text that isn't cut off.

<img width="368" alt="image" src="https://github.com/user-attachments/assets/d535b86c-225d-4d81-83ba-a9c36938ff3d">

**Comment by kartik-raj7** [comment]
Hey @Kitenite can I take this up !

**Comment by Kitenite** [comment]
@drfarrell , what happens when the text is really long?
<img width="1728" alt="Screenshot 2024-09-04 at 9 32 06 PM" src="https://github.com/user-attachments/assets/27258839-5f77-418c-a545-79938a66bd34">
