### ISSUE TITLE
[FEAT] Style layers and their parent group

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#276]
As an enhancement to the UI, it would be great if we could better designate a selected parent group. Ideally, the layers feel part of a rounded-corner group with the selected layer as the brightest. 

The specific tailwind classes are listed in the annotated mockups below.

![image](https://github.com/user-attachments/assets/b8be8adf-23f5-4437-bb36-a975ed650b13)

![image](https://github.com/user-attachments/assets/0be2770e-c25b-4055-90b8-603d07138845)

![image](https://github.com/user-attachments/assets/7a612984-dc2b-43f4-90d0-0033196e2e09)

**Comment by drfarrell** [comment]
<img width="319" alt="image" src="https://github.com/user-attachments/assets/d64f2ba9-6b6b-4e33-bf4c-68fc0d9243d7">

An example of how this would look for layer text that is close to the right side of the panel.

**Comment by abhiroopc84** [comment]
@drfarrell can I work on this?

**Comment by Kitenite** [comment]
@abhiroopc84 have at it! 
Here's where the layers tree lives
https://github.com/onlook-dev/onlook/blob/983c7907fe42f626ea58148fb1c7228e7f4e95d5/app/src/routes/editor/LayersPanel/LayersTab.tsx#L89

This is the layers library we're using https://github.com/brimdata/react-arborist

**Comment by abhiroopc84** [comment]
@Kitenite anything left to be worked on in this issue?

**Comment by Kitenite** [comment]
Looks good I'll close it. @drfarrell fyi in case it should be reopened.
