### ISSUE TITLE
[Bug] Holding shift occasionally outlines elements in the UI 

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#278]
Holding down shift and clicking on elements in the UI occasionally adds a white border around those elements. Holding shift and clicking should not outline any element in the Onlook UI.

<img width="343" alt="image" src="https://github.com/user-attachments/assets/2b6b9692-d8f7-4a62-b3e6-7b6663db3b77">

**Comment by Moshyfawn** [comment]
This is still the default accessibility behaviour of the browser _(Chromium specific)_, which might be better disabled by default and only enabled on specific interactive elements where it makes sense, as Onlook is a desktop application where focus is handled differently to web platforms.

**Comment by drfarrell** [comment]
Ah thanks for the explanation! I didn't know what it was.

**Comment by abhiroopc84** [comment]
Hey @drfarrell, I'd like to work on this, could you assign it to me?

**Comment by Kitenite** [comment]
All yours @abhiroopc84!

**Comment by drfarrell** [comment]
Seems like it works! Thanks @abhiroopc84
