### ISSUE TITLE
[Bug] Public security reporting

### ISSUE THREAD

**Issue by szepeviktor** [onlook-dev/onlook#282]
#### Describe the bug

🛑 Public reporting seems very dangerous.
https://github.com/onlook-dev/onlook/blob/880f02d70c98735ce85953d3c5dcecc45b7d82ac/SECURITY.md?plain=1#L3

Please consider another way, e.g. contact@onlook.dev

**Comment by Kitenite** [comment]
@szepeviktor good call, updated it to email us instead :)
