### ISSUE TITLE
[FEAT] Highlight "Review & Publish Code" button after changes are made

### ISSUE THREAD

**Issue by Eejya** [onlook-dev/onlook#290]
#### Expected behavior

If Onlook is detected on the project:
 * The "Review and Publish Code" button is highlighted after any changes have been made by the user 

If Onlook is **not** detected on the project:
  * The "Review & Publish Code" button is highlighted in Red and when clicked, displays an alert that Onlook isn't set up

**Comment by drfarrell** [comment]
I need to design this up
