### ISSUE TITLE
[bug] The main window starts off-center on startup

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#307]
The window ideally starts in the center of the screen when the app loads, not like the screenshot below

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/2723ee2a-4e95-4684-9a8d-c2ce724da9a0">

**Comment by ahp64** [comment]
Can I take this issue?

**Comment by Kitenite** [comment]
@ahp64 go for it!

**Comment by stephenm7777** [comment]
I can take this if you're cool with it

**Comment by Kitenite** [comment]
For sure @stephenm7777 go for it. It might not be very straightforward but happy to talk through a solution

**Comment by Kitenite** [comment]
@stephenm7777 , how's it going? Do you need any support on this?

**Comment by ahp64** [comment]
Hi, I've been busy the past few weeks but if the issue is still unresolved, I'm more than willing to take it back.

**Comment by Kitenite** [comment]
Back at it again, go for it @ahp64 !

**Comment by Kitenite** [comment]
Merged @ahp64! Nice work. Shouted you out in the Discord as well :D
