### ISSUE TITLE
[bug] Need to be able to delete and clear text

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#354]
#### Describe the bug
Sometimes text can not get cleared

**Comment by drfarrell** [comment]
May also be relevant but if you delete all the text in an element the element goes away from the canvas but still exists in the layers. Kinda an edge case. Framer removes the text layer entirely if there's no text in it.

**Comment by Kitenite** [comment]
I wonder if we actually should remove the node in this case. It could be there for placeholder purposes or have some styling attached to it. May leave it empty until emerging request for removing the node entirely
