### ISSUE TITLE
[bug] The pointer triangle animation is not in sync with the long layer name animation

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#360]
See how the triangle animates in after the wordbox does

![Export-1726451436560](https://github.com/user-attachments/assets/ce372360-30ed-407b-ae9a-350dd9a957f6)

**Comment by Sai-Manikanta-Andey** [comment]
Hey I would like to work on it !

**Comment by katungi** [comment]
Hey @drfarrell, Can I take this one?

**Comment by Kitenite** [comment]
Go for it @katungi

**Comment by stephenm7777** [comment]
I can give this a shot

**Comment by Kitenite** [comment]
@stephenm7777 , I did assign this to @katungi  already. Anything from here that you'd be interested in instead? https://github.com/onlook-dev/onlook/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by stephenm7777** [comment]
I fixed it but I can try something else too, I'll take a look

**Comment by Kitenite** [comment]
@stephenm7777 baller! Lmk if you need more info/support on any of the existing tickets :)

**Comment by stephenm7777** [comment]
fs bro
