### ISSUE TITLE
[feat] When an item is "deleted" from a page, show a toast

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#363]
Show a toast like this with copy along the lines of

**Element Hidden**
To completely delete the item, go into code so you don't accidently break your app. 

Applies to #361 

<img width="555" alt="Screenshot 2024-09-16 at 12 03 26 PM" src="https://github.com/user-attachments/assets/4c020f5b-d4b5-4c5d-9f5f-e0dff41cdab9">

**Comment by cleobnvntra** [comment]
Hello @drfarrell ! I would like to give this issue a go, can I please get this issue assigned to me?

**Comment by Kitenite** [comment]
@cleobnvntra, this issue was actually recently completed. Are there any other you'd like to pick up instead?

**Comment by cleobnvntra** [comment]
@Kitenite oh was it? I forked the repo and tried it out, the delete functionality was there but not the toast, as mentioned by the issue. Although, I'm still interested in contributing, so I'll go look for another issue to pick up!

**Comment by Kitenite** [comment]
@cleobnvntra before we were hiding elements by default so we wanted to warn the user. But now we actually delete the element so we're warning them upfront. Yes let me know what else you'd like to pick up instead :)
