### ISSUE TITLE
[feat] "Hide" or "Show" Eyeball icon on the layers list

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#364]
Allow users to toggle whether a layer is visible or not in the layers panel. 

- Use a Radix eyeball icon to the right of the layers panel.
- When a layer is tucked away inside a parent layer that is hidden, collapse the list of layers and if the layers list is open, make the layer name colors a darker shade of grey.

![Export-1726502996851](https://github.com/user-attachments/assets/289079ea-f2c0-4c54-a8a1-ef5415d5be2b)

**Comment by katungi** [comment]
Hey @drfarrell , and @Kitenite, can I take a crack at this one?

**Comment by Kitenite** [comment]
@katungi, go for it! Don't worry about the actual hide element logic. I can help with that after UI.

**Comment by drfarrell** [comment]
@katungi I'm going to open up the issue to other contributors to potentially take on during hacktoberfest – lmk if you'd still like to take it on!

**Comment by RaghavGanesh7** [comment]
Hi @drfarrell @Kitenite ! I'd love to contribute to this issue as part of hackoberfest.

**Comment by Kitenite** [comment]
Have at it @RaghavGanesh7 ! I can add the functionality separately once you're done
