### ISSUE TITLE
[bug] swc_core / @swc/core version incompatibility

### ISSUE THREAD

**Issue by smndtrl** [onlook-dev/onlook#378]
#### Describe the bug

The SWC plugin fails. I assume the WASM interface changed and somehow the correct versions are not enforced. What is the correction version of the @swc/xxx packages? Could not find a mention of @swc/core in the repo anywhere.
I get `@swc/core@1.7.26` in our `pnpm-lock.yaml`.

```
Caused by:
    0: failed to invoke `/workspaces/product-ui-next/node_modules/.pnpm/@onlook+nextjs@2.1.0/node_modules/@onlook/nextjs/plugin.wasm` as js transform plugin at /workspaces/product-ui-next/node_modules/.pnpm/@onlook+nextjs@2.1.0/node_modules/@onlook/nextjs/plugin.wasm
    1: failed to run Wasm plugin transform. Please ensure the version of `swc_core` used by the plugin is compatible with the host runtime. See https://swc.rs/docs/plugin/selecting-swc-core for compatibility information. If you are an author of the plugin, please update `swc_core` to the compatible version.
```

**Comment by Kitenite** [comment]
@smndtrl , what version of next are you running? Does it go away if you update next to latest (if possible)?
This seems to happen for versions lower than 14.1 as they seldom break the swc plugin ecosystem

**Comment by smndtrl** [comment]
I just discovered that for some reason (probably react compiler) we moved onto the 15 RC branch. My bad! I'll have to wait and see than until onlook can support that because a quick switch of next to 14.2.12 did not resolve it.

Feel free to close
