### ISSUE TITLE
[bug] "Open component in Zed" creates empty buffer instead of existing file

### ISSUE THREAD

**Issue by Moshyfawn** [onlook-dev/onlook#415]
#### Describe the bug

When using the "Open component in Zed" button, an empty buffer is created instead of opening the existing file. The file name is appended with row and column numbers.

#### Steps to Reproduce

1. Generate a default Next.js project using Onlook:
   ```bash
   npx onlook create <project-name>
   npx onlook setup
   ```
   Then run the project with `bun run dev`

2. In the running project, locate and select the "Welcome to your app" heading in Onlook
3. Click the "Open in Zed" option
4. Observe the result in Zed: an empty buffer opens with the filename `page.tsx:17:9`

#### Expected Behavior

Clicking "Open in Zed" should open the existing `app/page.tsx` file in Zed, positioning the cursor at the specified row and column number.

#### Actual Behavior

An empty buffer is created with the filename `page.tsx:17:9`, containing no content from the actual file.

#### Environment

Zed: v0.156.0 (Zed Nightly 675673ed5462711916e7824528698fc235d679b2)
OS: macOS 14.6.1
Memory: 18 GiB
Architecture: aarch64

#### Screenshot

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/f68520cf-c3a9-48c6-997a-987e1da65db3">

**Comment by Moshyfawn** [comment]
Related to zed-industries/zed#14820

**Comment by Kitenite** [comment]
Hmm, that's annoying. Looks like we need to roll this back (and use file only) until Zed fixes this. 
 Thanks for opening @Moshyfawn

**Comment by Kitenite** [comment]
Fixed in #419 . Thanks for the report @Moshyfawn and hunting down that zed issue :)
