### ISSUE TITLE
[bug] supabase callback and deep link in windows

### ISSUE THREAD

**Issue by hitaspdotnet** [onlook-dev/onlook#428]
`open-url` is not triggering in win32.

Windows requiring additional code in order to open the contents of the protocol link within the same Electron instance
https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata

solution:

```ts
    app.on('second-instance', (_, commandLine) => {
        if (mainWindow) {
            if (mainWindow.isMinimized()) {mainWindow.restore()};
            mainWindow.focus();
        }
        const url = commandLine.find(arg => arg.startsWith(`${APP_SCHEMA}://`));
        if (url) {
            handleAuthCallback(url);
        }
    });
```

**Comment by Kitenite** [comment]
@hitaspdotnet thanks for opening the issue. Seems like in this case, we'd rather force single instance instead such that windows have the same expected behavior as MacOS?

**Comment by hitaspdotnet** [comment]
we can check the platform too:

```ts
if (url && (process.platform === 'win32')) {
            handleAuthCallback(url);
        }
```

**Comment by Kitenite** [comment]
Merged a fix @hitaspdotnet thanks for reporting!
