### ISSUE TITLE
[bug] Nothing Happens when I Click on Onlook Icon in Desktop App for Windows

### ISSUE THREAD

**Issue by kartik-raj7** [onlook-dev/onlook#436]
#### Describe the bug

In Windows on clicking the onlook logo on the top left nothing happens.

![image](https://github.com/user-attachments/assets/974a54e5-a496-4c68-bee9-c810dbb1d604)

**Comment by Kitenite** [comment]
Hmm, could you check your settings for what version this is? I know we're not auto-updating on windows correctly for older versions

**Comment by Kitenite** [comment]
This may be solved with the canvas bug

**Comment by Kitenite** [comment]
Can no longer reproduce with the canvas fix. Please reopen if it's still happening.
