### ISSUE TITLE
[bug] In Windows nothing shows on main screen when I load up the project

### ISSUE THREAD

**Issue by kartik-raj7** [onlook-dev/onlook#437]
#### Describe the bug

When I run the project and open it in desktop app of windows nothing really shows. 

![image](https://github.com/user-attachments/assets/f824677f-ed98-48bb-86d1-c4259b48d534)

I was running the demos/next project present in onlook codebase.

**Comment by Kitenite** [comment]
We identified this as a zoom range issue. https://github.com/onlook-dev/onlook/pull/446 adds max min zoom and pan ranges. This should help maintain track of the windows
