### ISSUE TITLE
[feat] Custom Header Icons in the layers panel

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#465]
<img width="781" alt="image" src="https://github.com/user-attachments/assets/a9484453-b6d6-4155-bfcb-8c18a580c798">

Custom icons for header levels so that we don't have to rely on plain written text to demonstrate to a user what level header they have selected. 

Note how before we used to write "p " or "h1 ". Now we can use the icons to save more space. 
<img width="865" alt="image" src="https://github.com/user-attachments/assets/01431df2-3636-4a27-b12b-ba449f06bb0e">

This likely means uploading the assets, then adjusting the NodeIcon.tsx file to accommodate the conditions for the assets we have today.
<img width="773" alt="image" src="https://github.com/user-attachments/assets/08862fbf-a874-4b7d-9016-2b9a276ada19">

The assets themselves are two-parts: The base H and the number. It would be awesome if we could use the tailwind classes to style the base H and Number, but that may require some SVG work. 

Nevertheless, here are the .svg files for H1-6
![H1](https://github.com/user-attachments/assets/5ec396c8-fb42-465e-846f-77340a5cc971)
![H2](https://github.com/user-attachments/assets/19bfb1a4-0603-434f-8b80-53b9bdff5617)
![H3](https://github.com/user-attachments/assets/ac9ce459-330a-4b53-ae2e-b20d75beabe5)
![H4](https://github.com/user-attachments/assets/3377a747-0608-422b-ad7e-1c9f4306d5db)
![H5](https://github.com/user-attachments/assets/3859ed5e-ae37-406d-87d3-811f8f774546)
![H6](https://github.com/user-attachments/assets/ca3c7e15-ab38-4385-8e68-ef71502630cf)

**Comment by abhiroopc84** [comment]
Hey @drfarrell, could you assign this to me?

**Comment by Kitenite** [comment]
@abhiroopc84 go ahead!
