### ISSUE TITLE
[feat] Make the DEL key also work like the BACKSPACE key

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#474]
Allow users to delete elements using the DEL key, primarily used on Windows.

Pretty much replicate the BACKSPACE key functionality.

**Comment by belkhoujaons** [comment]
can you assign this to me and if possible, describe more what element and where I could find it ?

**Comment by Kitenite** [comment]
@belkhoujaons for sure!

**Comment by Kitenite** [comment]
Merged, nice work @belkhoujaons !
