### ISSUE TITLE
[feat] Infinite Canvas Zoom controls

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#475]
Add in Zoom controls in the upper right navigation bar. 

<img width="512" alt="image" src="https://github.com/user-attachments/assets/8c98aa3d-c34a-48b9-ae69-5008bcc4fd11">

Matching some of the levels here ideally with the dropdown:

<img width="250" alt="image" src="https://github.com/user-attachments/assets/f2db5d58-99c4-446d-8986-4f30b738f1aa">

**Comment by sairiteshdomakuntla** [comment]
hello @drfarrell , can you assign this to me?

**Comment by Kitenite** [comment]
Go ahead @sairiteshdomakuntla !

**Comment by drfarrell** [comment]
@sairiteshdomakuntla how is it going? Do you need any help?

**Comment by RaghavGanesh7** [comment]
Hi @drfarrell @Kitenite , If this task is inactive would love to pick it up if possible :)

**Comment by Kitenite** [comment]
Go for it @RaghavGanesh7

**Comment by drfarrell** [comment]
Closing as this was completed.
