### ISSUE TITLE
[feat] Ability to rename a project from the projects page

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#485]
<img width="438" alt="image" src="https://github.com/user-attachments/assets/8ceaa6a5-19d1-48e8-a709-33bf5c52e4cf">

Ideally add in a button to this project settings drop down that lets you rename a project in an input dialog like: 
<img width="608" alt="image" src="https://github.com/user-attachments/assets/bdf50e59-f567-4ba7-9e90-20b1c62af704">

but simpler

**Comment by dajana212** [comment]
Hello, is this issue free? I would like to work on this issue, can you assign it to me?

**Comment by dajana212** [comment]
Thank you, I will start work on that.

**Comment by Kitenite** [comment]
Have at it @dajana212 , keeping in mind the project name can be updated using this function. You can see an example usage in the delete functionality

https://github.com/onlook-dev/onlook/blob/090b27578b691e7ba40e815b716eb75365ad1808/app/src/lib/projects/index.ts#L49

https://github.com/onlook-dev/onlook/blob/090b27578b691e7ba40e815b716eb75365ad1808/app/src/lib/projects/index.ts#L49

**Comment by dajana212** [comment]
@Kitenite I just opened PR: https://github.com/onlook-dev/onlook/pull/515
Please check once you have a time.

**Comment by Kitenite** [comment]
Hey @dajana212 , sorry I didn't see the question before merging. 
Good thinking. Let's enforce a min character limit of 1. I'll keep this issue open if you'd like to also add that logic. Thanks :)

**Comment by dajana212** [comment]
@Kitenite thank you for response, I will prepare new PR with this functionality.

**Comment by Kitenite** [comment]
Nice thanks for the quick turnaround. Merged!
