### ISSUE TITLE
[feat] Editor's theme switcher

### ISSUE THREAD

**Issue by hitaspdotnet** [onlook-dev/onlook#488]
#### Describe the feature:
If user's system is in light mode, onlook is ugly:
![image](https://github.com/user-attachments/assets/9b112ca8-5f21-4771-8aa8-a9607891d9b9)
_Windows 11, light-mode desktop_

Switch between dark and light mode or inherit system mode in editor.
dependencies:

- [x] onlook-dev/onlook/issues/489
- [x] onlook-dev/onlook/issues/490

**Comment by Kitenite** [comment]
Yuck, I didn't think we enable light mode at all
