### ISSUE TITLE
[bug] Tokens/Colors refactoring

### ISSUE THREAD

**Issue by hitaspdotnet** [onlook-dev/onlook#489]
#### Describe the bug
Some tokens do not follow the Tailwind standard. The Tailwind standard says that alpha in colors should be from 50 to 950 and that 50 should be the lightest and 950 should be the darkest.

also, sort colors from light to dark. we have some unsorted colors in tokens.

![image](https://github.com/user-attachments/assets/a87df41e-414f-4dea-965a-235a72a457c6)

**Comment by Kitenite** [comment]
I agree that we should swap this to be compliant
