### ISSUE TITLE
[feat] Project dropdown within the editor

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#498]
Add a button to the right of the project name that is a dropdown icon, and when it's clicked it reveals a menu. Right now we only have one menu item which is "open project folder" but this is pretty much the same functionality that we have on the projects page, so you should be able to pretty easily make it. 

<img width="541" alt="image" src="https://github.com/user-attachments/assets/a64fcf79-afaa-46a6-950a-3823a1ab55fa">

When the project title is clicked and the dropdown is active, the text should be text-active as well as the icon (icon-active)

**Comment by Kitenite** [comment]
For sure @shernoble , go ahead!

**Comment by belkhoujaons** [comment]
I already worked on this one, check pull request please @Kitenite

**Comment by Kitenite** [comment]
Hey @shernoble, 
Since @belkhoujaons already put in a PR at it looks done, I'll merge that in and close this. 
Thanks for the contributions both :)
