### ISSUE TITLE
[feat] Double-clicking on the sides of an element to automatically adjust width style

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#503]
- Double-click on an edge of an element to set it to "Hug" 
- Double-click on an edge of an element while holding "option" or "ALT" to set it to "Fill" 

Inspired by:
https://x.com/miguelsolorio_/status/1844442223318090043

Could also be related to #101

**Comment by TheShiveshNetwork** [comment]
Hey @drfarrell I'm interested to work on this, can this issue be assigned to me?

**Comment by Kitenite** [comment]
This is gonna be a tricky one @TheShiveshNetwork let me know of any roadblocks you run into with this in the Discord. 
I think this is probably not a good first issue @drfarrell

**Comment by drfarrell** [comment]
Hey @TheShiveshNetwork how's it going? Need any help?

**Comment by drfarrell** [comment]
@TheShiveshNetwork I'm going to unassign you from this just so we can open it up for other contributors. Let me know if you'd still like to work on it!
