### ISSUE TITLE
[feat] Move the Settings page navigation into the profile dropdown

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#518]
Add a dropdown menu item for "Settings" here and remove the Project / Settings switcher in the center of the projects view.

<img width="347" alt="image" src="https://github.com/user-attachments/assets/e5791397-00f2-4147-aab9-ab28e7f5822f">

Remove this navigation from the projects view.
<img width="334" alt="Screenshot 2024-10-13 at 10 36 15 PM" src="https://github.com/user-attachments/assets/f16b1078-93d0-44f9-be27-5e1bad798a9d">

Also, would be nice to add a Gear icon for settings and an Exit icon in the dropdown menu next to the right items.

**Comment by j-mahapatra** [comment]
Can you please assign me this issue?
