### ISSUE TITLE
[feat] Hotkey – Shift + Arrow Up or Arrow Down to move an item in a stack

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#519]
When a layer is in a flex column or row, allow the user to move it up and down the layers list within the flex stack using the Shift + Arrow Up or Arrow Down hotkey. Do NOT allow the layer to escape the stack – when the layer hits the first or last item in the array, don't let it go outside of the parent div. 

This will involve updating app/common/hotkeys.ts 

Related to #193. 

Feature: Add Shift + Arrow hotkeys for layer reordering within flex stacks.

Description:

When a layer is in a flex column or row, allow the user to move it up or down the layers list within the flex stack using the Shift + Arrow Up or Arrow Down hotkey. Do NOT allow the layer to escape the stack – when the layer hits the first or last item in the array, don't let it go outside of the parent div.

Expected Behavior:

- Layers can be reordered within the flex stack using the hotkeys.
- Layers do not escape the parent container when reaching the top or bottom.
- Changes should dynamically reflect in the UI and the underlying DOM structure.

Implementation Notes:

- Update app/common/hotkeys.ts to handle the new hotkeys.
- Check layersList.tsx and domTree.ts for potential updates to reflect layer reordering in the DOM.
- Ensure compatibility with existing undo/redo functionality.

Testing Criteria:

- Verify hotkey functionality works in both flex column and flex row layouts.
- Ensure layers remain within the parent div in all cases.
- Test functionality in nested flex stacks.
- Validate across browsers and screen sizes.

Related Issues: #193

Additional Notes:
This feature aims to enhance usability for designers and improve workflow efficiency.

**Comment by aPassie** [comment]
I wanna work on this, can you assign me.
Thanks for considering

**Comment by alexandreantunesmnds** [comment]
Hi @drfarrell can I work on this please ?

**Comment by Kitenite** [comment]
Go for it @alexandreantunesmnds

**Comment by Kitenite** [comment]
@alexandreantunesmnds I will unassign you from https://github.com/onlook-dev/onlook/issues/567 for now since you already have this #519 picked up. Sorry for the confusion there.

**Comment by drfarrell** [comment]
Hey @alexandreantunesmnds how's it going? Need any help?

**Comment by drfarrell** [comment]
@alexandreantunesmnds I'm going to unassign you from this just so we can open it up for other contributors, but let me know if you'd still like to work on it!

**Comment by alexandreantunesmnds** [comment]
Hi @drfarrell ! Thank you for the update and no worries, I completely understand. I had actually run into a few challenges implementing the hotkey feature and wasn’t able to dedicate as much time as I’d hoped. If it’s okay, I’d still love to help, even if it’s on another issue or if there’s any way I could support other contributors working on this. Thanks again!

**Comment by happymvp** [comment]
@alexandreantunesmnds just describe your findings, what you found and where you got stucked
