### ISSUE TITLE
[bug] Make the logo the proper foreground color for light / dark mode

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#531]
Need to make the logo on the Projects top bar and the sign-in page the correct color so it stands out against the background of the app depending on light / dark mode. 

<img width="449" alt="image" src="https://github.com/user-attachments/assets/d588d42b-a389-45f6-bdd1-44953d4ada67">

The logo color should use the foreground class (black logo on white background, white logo on black background)

**Comment by Utzig26** [comment]
I can work on it
