### ISSUE TITLE
[feat] Edit App Hover State on Projects View

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#532]
Add in hover state over the projects that shows a button. Ideally the button does a super short animation in as the overlay animates in subtly on hover.

![image](https://github.com/user-attachments/assets/52cfa6a7-8f79-4b6f-9ead-1157209c7055)

**Comment by thvroyal** [comment]
Hi @drfarrell, can I work on it?

**Comment by Kitenite** [comment]
Go for it @thvroyal!

**Comment by thvroyal** [comment]
I just created PR https://github.com/onlook-dev/onlook/pull/538 to resolve this issue. Please take a look if you have time @drfarrell @Kitenite 
Many thanks,

**Comment by Kitenite** [comment]
Nice work @thvroyal !
