### ISSUE TITLE
[feat] Swipe-animate the project setup flow using Framer Motion

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#533]
Using the lessons from https://animations.dev/, create reasonable, smooth animations for the steps that need to happen in the project setup flow.

![Export-1728952422776](https://github.com/user-attachments/assets/bcef62b3-001a-4349-a171-7edf1ed95ea3)

This likely requires a new component type with the animations. The animations should animate the height of the card, the animation from left-to-right, and the animation from right-to-left (animate back a step).

**Comment by 0xsommer** [comment]
I am going to work on that @drfarrell

**Comment by 0xsommer** [comment]
What do you think @drfarrell?


https://github.com/user-attachments/assets/ff62b502-d64c-4408-9d72-5c250218a6c6
