### ISSUE TITLE
[feat] Hold down alt/option to measure

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#540]
Allow a user to select an element, then hold down alt and mouse over other elements on the screen to see the distances between elements.

<img width="628" alt="image" src="https://github.com/user-attachments/assets/8202b23b-5ce1-480a-8267-c10a1605cd4e">

**Comment by thvroyal** [comment]
What a good UX to enhance! Can I work on it?

**Comment by drfarrell** [comment]
Sure thing! I'll assign you to it. Let us know if you need any help or have questions – you're welcome to join our discord and chat live there anytime :) https://discord.gg/ZZzadNQtns

**Comment by thvroyal** [comment]
Great, thanks! I'll get started on it right away. I'm already in and will chat if have any concerns

**Comment by thvroyal** [comment]
I completed 50% of the task before pausing due to personal matters. I resumed work yesterday and plan to create a pull request shortly, possibly tomorrow.

**Comment by thvroyal** [comment]
Hey @Kitenite @drfarrell, I have a PR https://github.com/onlook-dev/onlook/pull/624 for this. There are several changes and complex logic for measuring distance. Please help me review it and let me know if anything is wrong.
