### ISSUE TITLE
[feat] Animate and rotate the project menu arrow chevron icon

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#543]
When the project menu is opened, animate and rotate the arrow icon 180º to point up.
<img width="256" alt="image" src="https://github.com/user-attachments/assets/bcf3edb7-11a9-4a81-a100-8e8dd5d5586f">

<img width="277" alt="image" src="https://github.com/user-attachments/assets/0e9d321c-fefc-402e-8191-350b79b701bf">

**Comment by thvroyal** [comment]
Hi @drfarrell, I just created PR https://github.com/onlook-dev/onlook/pull/544 for it, please take a look if you have time!
