### ISSUE TITLE
[bug] Creating new project on Windows can't cd absolute path

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#547]
#### Describe the bug
when the project folder is on windows, D: drive, you can't simply cd to the location.. 

So you have to:
`D: && cd D:\Users\...\onlookdemo && npm run dev`

This should be handled here 
https://github.com/onlook-dev/onlook/blob/main/app/src/routes/projects/ProjectsTab/Create/New/Run.tsx#L22

**Comment by Utzig26** [comment]
I can work on it

**Comment by Kitenite** [comment]
Awesome @Utzig26  go for it!
