### ISSUE TITLE
[feat] UI for our AI Chat – no functionality required

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#550]
Implement the following design and its components in the "Ai Styles" Placeholder section of the right properties panel.

<img width="671" alt="image" src="https://github.com/user-attachments/assets/1fa2a160-3cb6-4bf3-b617-30231a65ee7c">

Here's a more detailed screenshot:
<img width="796" alt="image" src="https://github.com/user-attachments/assets/2c16c9b6-5a4e-4949-b2b5-6f91a3ca64fc">

This is the design for the "chat history" button. The "chat history" button should have a hover state label that says "Chat History" and be in an "active" state when the side panel is open. It would be ideal if there was a search bar in the top panel, but that can be added in a later PR. It is OK if the width of the chat history is a bit larger that the properties panel. The "Plus" button is a "New Chat" button and should have a hover state label on it too.

<img width="987" alt="image" src="https://github.com/user-attachments/assets/8d972016-3cdc-4ba5-8cb6-37efa92cb72c">

Please use the proper tokens for foreground / background, as our app is in light / dark mode now.

Also use proper text-sizing tokens from our app tokens indicated by this chart below. Use your best judgement – we can clean up the styles easily if there are issues.
<img width="730" alt="image" src="https://github.com/user-attachments/assets/d65a1301-bc77-4063-82d6-42ba26e3d566">

**Comment by tanmaytare** [comment]
i would like to work on it can you assign it to me

**Comment by abhiroopc84** [comment]
@Kitenite @drfarrell could you assign this to me?

**Comment by Kitenite** [comment]
👍  @abhiroopc84
