### ISSUE TITLE
[feat] Rename project from the project menu in the editor

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#551]
Two parts, part 1 is for beginners, and part 2 is more intermediate.
1. Add in an item here that allows the user to reliably rename their project just like they can on the projects view. #515 
2. Allow the user to double-click a project name and rename it as if it were an input. Use the initial project name as a placeholder text. If the user hits enter, save the name. If the user his ESC, cancel the name change.

<img width="343" alt="image" src="https://github.com/user-attachments/assets/cd26d7fa-d6ab-4340-868f-0f52f7a1a517">

**Comment by sambhavnrana** [comment]
Would like to work on it @drfarrell

**Comment by sambhavnrana** [comment]
**Issue #515:**  Project Renaming Functionality
The current implementation of the project renaming feature has some limitations:

Local Device Name Change: Renaming a project only updates the name in the desktop application, and does not change the name locally on the device.
Deletion Behaviour: When a project is deleted from the application, it does not remove the project from the device.

To enhance user experience, should I focus on addressing these issues first, or should I continue working on assigned features only ?

**Comment by Kitenite** [comment]
Hey @sambhavnrana , 

The current behavior is acceptable for now. We want to scope the name changes to only the app  for users who are importing an existing project. Deleting or renaming their project folder would be unexpected behavior. 

We may introduce explicit filesystem rename and delete later down the line. I like the user-centric line of thinking though :)
