### ISSUE TITLE
[feat] Add support for One framework and Tamagui 

### ISSUE THREAD

**Issue by ansarizafar** [onlook-dev/onlook#552]
#### Describe the feature
Onlook is an amazing project. Is there any plan to add support for One framework  https://onestack.dev/ and Tamagui https://tamagui.dev/

**Comment by Kitenite** [comment]
Hey @ansarizafar,
Seems like One is using Vite so the manual setup will work (1 line change). We can also prioritize an official GUI import support as well
https://github.com/onlook-dev/onlook/wiki/How-to-set-up-my-project%3F#do-it-manually

**Comment by Kitenite** [comment]
Onlook will now work for any react framework with no setup. Let me know if this still doesn't work :)
