### ISSUE TITLE
[bug] Wrong background color in delete item pop-up.

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#554]
Color styling in lightmode needs to be fixed. You can refer to the project setup cards for the right tokens needed for pop-ups to be compliant with dark / light mode. bg-background-onlook is likely what needs to be used here.

<img width="761" alt="image" src="https://github.com/user-attachments/assets/ff98a063-d8e3-481f-a16e-87223844b6cb">

**Comment by aryanbroy** [comment]
working on it
