### ISSUE TITLE
[feat] Add a link to a YouTube tutorial to help people run a project during project setup

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#561]
#### Describe the feature

Add in a button that navigates the user to https://youtu.be/RjFBUkVfy1E?t=45&feature=shared in their browser

<img width="653" alt="image" src="https://github.com/user-attachments/assets/cef5d420-f96e-4634-ad79-d99e7af0312c">

Mockup:
<img width="633" alt="image" src="https://github.com/user-attachments/assets/6603b3d0-a5b8-4896-a7b1-286304c90e52">

Preview image:
![image](https://github.com/user-attachments/assets/9ae28a0f-1f3e-4055-a85a-0049feabbf57)

**Comment by aPassie** [comment]
Can you assign this issue to me.
Thanks for considering

**Comment by drfarrell** [comment]
@aPassie please ask to work on one issue at a time. I'll assign you to this one and remove your comments from the others so that other people can have a chance to do them. If you finish this issue, then we can assign you a new one 😄

**Comment by aPassie** [comment]
Sure, and sorry for multiple assign requests.

**Comment by J9414** [comment]
Hello @drfarrell if this task is not assigned to @aPassie . 
I would like to do it, I have done some work on it as attached in below screen shot 

![Screenshot from 2024-10-17 11-46-17](https://github.com/user-attachments/assets/22d09014-b05f-4abc-8eef-08ec6c78cb49)

as you can see image is missing because image that you suggested i cant open in or use it.

**Comment by aPassie** [comment]
![image](https://github.com/user-attachments/assets/b2af09f4-a638-4d48-8d64-8589cfc28971)
I have solved the issue, but its not fetching thumbnail image from API, I think there is no image there, So should raise a linked pull request or should i wait till you update API.

**Comment by aPassie** [comment]
@drfarrell I can also add this thumbnail image.
![image](https://github.com/user-attachments/assets/3c477db0-f8f9-4348-87e1-15d401d34c9d)

**Comment by drfarrell** [comment]
> @drfarrell I can also add this thumbnail image, If you want.
> 
> ![image](https://github.com/user-attachments/assets/3c477db0-f8f9-4348-87e1-15d401d34c9d)
> 
> 

Yes just go ahead and use this image. No need to use the API image. Looks great btw!

**Comment by aPassie** [comment]
I have raised a PR after doing the changes.
Have a good day!
