### ISSUE TITLE
[bug] Layer panel name tooltip errors

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#562]
![Export-1729102985054](https://github.com/user-attachments/assets/79dbd570-480c-47a7-ae46-0a96e263b603)

Two errors

1. The arrow pointing to the text loads in AFTER the rest of the tooltip
2. Occasionally the tooltip will go too far to the right on hover. It's very inconsistent. Perhaps it's appending it to the end of the string location.

**Comment by aPassie** [comment]
I can do this, can you assign this to me.
Thanks for considering

**Comment by drfarrell** [comment]
I'll assign you to this one as well if you'd like to include it in your other assigned issue #561

**Comment by drfarrell** [comment]
@aPassie how is it going? Do you need someone else to take this on?

**Comment by aPassie** [comment]
@drfarrell assign it to someone else, as I wouldn't be able to solve this issue for another week.
Sorry for wasting your time.
