### ISSUE TITLE
[feat] Allow the ability to drag-in new elements from the toolbar

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#566]
<img width="302" alt="image" src="https://github.com/user-attachments/assets/4e3fbaf5-32ed-4e4c-80de-2d0adb1556cf">

Allow users to drag-in a standard size 100px X 100px Div or Text box from the bottom toolbar.

**Comment by iNerdStack** [comment]
Hello @drfarrell, 
I am interested in working on this, can you give more context to this task and more specifics on this ?

**Comment by alexandreantunesmnds** [comment]
Hi can i solve this issue ?

**Comment by Kitenite** [comment]
@iNerdStack yes exactly

**Comment by drfarrell** [comment]
> @iNerdStack yes exactly

To clarify, The user can click and drag the div button and it will drag a **div** of standard size onto the page, not a **div icon**. 

The same for the text box.

**Comment by iNerdStack** [comment]
Understood. On it now

**Comment by iNerdStack** [comment]
I have some updates while working on this issue

I am experiencing difficulties implementing drag and drop functionality on Electron's  [`<webview>`](https://www.electronjs.org/docs/latest/api/webview-tag) element. The toolbar draggable item works but doesn't fire an event when it is dragged over the `<webview>`.

## Current situation
- The [`<webview>`](https://www.electronjs.org/docs/latest/api/webview-tag) element does not appear to be a valid drop target. [https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API](url)
- Drag events (dragover, dragenter, drop) are not triggering on the webview as it is not part of the element.
- Attempts to use an overlay div on top of the webview to capture drag events  was also not unsuccessful.

```jsx
const Frame = () => {
  const handleDragOver = (e) => {
    e.preventDefault();
    console.log('Drag over');
  };

  const handleDrop = (e) => {
    e.preventDefault();
    console.log('Drop event fired');
    // Logic to insert element into webview
  };

  return (
    <div onDragOver={handleDragOver} onDrop={handleDrop}>
      <webview
        src="http://example.com"
        style={{ width: '800px', height: '600px' }}
      />
    </div>
  );
};
```

## What I've Tried
1. Adding drag event listeners directly to the [`<webview>`](https://www.electronjs.org/docs/latest/api/webview-tag) element
2. Creating an overlay div on top of the [`<webview>`](https://www.electronjs.org/docs/latest/api/webview-tag) to capture drag events
3. Implementing drag handlers at a higher level (parent component of the webview)
4. Ensuring drag data is correctly set when starting the drag operation.
5. Checking for any interfering event listeners or CSS properties that might be blocking the events

[`<webview>`](https://www.electronjs.org/docs/latest/api/webview-tag) is Electron's webview tag is based on [Chromium's webview](https://developer.chrome.com/docs/extensions/reference/webviewTag/), which is undergoing dramatic architectural changes. This impacts the stability of webviews, including rendering, navigation, and event routing.
 
 as said in Electron documentation
 
 See other similar raised issues on Electron webview: [#8867](https://github.com/electron/electron/issues/8667), [#9377](https://github.com/electron/electron/issues/9377),

## Video Demonstration
Parent container triggers drop event with no issues, but doesn't when a dragged item is placed on the webview

https://github.com/user-attachments/assets/5a9af787-3e7a-40d0-b10a-9586d90479d9

**Comment by iNerdStack** [comment]
Right now, I am considering using the dropEnd event on the toolbar item and track mouse position relative to the webview, if outside the view do nothing, if inside programmatically access the webview or editorEngine and add the item.

**Comment by Kitenite** [comment]
@iNerdStack looking good. We have some conversion helpers here 
https://github.com/onlook-dev/onlook/blob/e3622a83dc672a1c7a368e72ab408e3265c9363d/app/src/routes/editor/WebviewArea/GestureScreen.tsx#L42-L60
