### ISSUE TITLE
[feat] Ultra subtle animations

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#568]
When a user clicks on this button, it'd be nice to trigger a small animation.

When clicked, rotate the arrow 360º
<img width="223" alt="image" src="https://github.com/user-attachments/assets/2d4c70ae-eb98-4916-b306-241534c6ab07">

When clicked, rotate the gear a couple degrees, and then back a couple degrees when unselected. 360º would be a bit excessive for this animation.
<img width="248" alt="image" src="https://github.com/user-attachments/assets/a9c77cd1-e928-4779-a71e-26c3093f9e9d">

What other subtle animations can we include in the UI?

**Comment by tanmaytare** [comment]
i would like to work on it , can you assign it to me

**Comment by drfarrell** [comment]
@tanmaytare I'm going to assign this to you and leave the other issue you commented open for other contributors. If you finish this up, then we can assign you another, but I want to leave some open to other contributors in the meantime 👍

**Comment by darshancn** [comment]
If this issue is not yet assigned to @tanmaytare, i want to work on this .Please can you assign it to me

**Comment by drfarrell** [comment]
@tanmaytare how is this going? It should be relatively simple but let me know if you need help.
