### ISSUE TITLE
[bug] Rename input needs to be refreshed when a new project is selected

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#569]
The Rename input carries over the value from the last project that was selected to be renamed, not the current one.

See in the screenshot how the default name in the input box is different from the project currently selected (sample testing)
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/c643f411-f67c-4fbc-b2d2-1f76b8ee0f73">

**Comment by karthik-script** [comment]
Hi @drfarrell , I can take a look. Please assign it to me.
Also, can you please add Labels on this for Hactoberfest? Thanks.
