### ISSUE TITLE
[bug] update issue

### ISSUE THREAD

**Issue by nzgl-g** [onlook-dev/onlook#575]
#### When attempting to update the Onlook application directly within the app, it unexpectedly deletes itself, requiring me to redownload it from the website to reinstall.
OS : win 11

**Comment by Kitenite** [comment]
@nzgl-g Sorry about that. This was an issue in version `0.0.38` and below. It should correctly auto-update now with your later version. Please let me know if this still happens.

**Comment by nzgl-g** [comment]
the issue still existed 
when open app update button pops up, after closing the app and open it again  dont find the app .

**Comment by Kitenite** [comment]
@nzgl-g dang, gotcha I will look at this

**Comment by Kitenite** [comment]
This should now be solved with the latest release. Thanks for the patience @nzgl-g 
https://github.com/onlook-dev/onlook/releases/tag/v0.0.49

**Comment by Kitenite** [comment]
Closed as this seems to be solved now. Please reopen if this persists

**Comment by nzgl-g** [comment]
> Closed as this seems to be solved now. Please reopen if this persists

ye , its working perfectly for now , thanks.
