### ISSUE TITLE
[feat] hide the upper nav-bar "forward" button if there's nothing to go forward to

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#580]
Ideally this button would animate-into view if there's an option to go forward.
<img width="518" alt="image" src="https://github.com/user-attachments/assets/c1ac4ba8-36b2-40f5-a81b-85941c06510e">
<img width="1327" alt="Screenshot 2024-10-17 at 5 10 31 PM" src="https://github.com/user-attachments/assets/4e81a02d-9523-42e2-b9c6-dca2adc9dfb0">

**Comment by j-mahapatra** [comment]
Opened a PR that will make the necessary changes. Apologies for not getting the issue assigned first (Took it up since nobody else was assigned). Please take a look.

**Comment by Kitenite** [comment]
No worries @j-mahapatra , thanks for moving quick. Merged!
