### ISSUE TITLE
[feat] Make the Zed logo black when the app is in light mode.

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#581]
Make the logo black for light mode and light for darkmode. 

This should be similar to #534 

<img width="298" alt="image" src="https://github.com/user-attachments/assets/b0a367e2-5d84-4a1e-8158-ae7c2fa1777f">

**Comment by Utzig26** [comment]
I worked on #534, I could work on this one too

**Comment by Yash-007** [comment]
I can also work on this issue.

**Comment by Utzig26** [comment]
Hey @drfarrell, both the VSCode and Cursor icons use a silver palette that works great in both light and dark modes. By changing the Zed logo to a similar idea, we achieve the following result:
| Dark | Light |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/59866540-eb8b-4cba-a3bf-75a2169334a8) | ![image](https://github.com/user-attachments/assets/cb77d0f0-4910-481d-aa0d-8c7ccfd6780e) | 

I just changed the .svg
| From this | To this |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/640e2306-00ea-40f9-8a28-9266162fa31f) | ![image](https://github.com/user-attachments/assets/3c6a0484-2fb6-467c-b8d8-99b084489b25)| 

It just took me a few minutes before I tried to write some code. If this is a valid solution, I can create a PR with the new SVG.

**Comment by Kitenite** [comment]
@Utzig26 please do! There's an existing PR as well but I like this clean solution :)

**Comment by drfarrell** [comment]
This seems to be solved #601
