### ISSUE TITLE
[feat] Add grid drag-and-drop support

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#584]
#### Describe the feature
Currently, we're handing drag positioning for flex or block only. We need to handle grid. 

Here is where we're handling the drag logic. The stub is the gray box that represents the future drop position. We need to calculate the correct position for the stub element in order to implement drag. 

I think this is a well-scoped problem (though difficult) so would be good for first-time contributor

https://github.com/onlook-dev/onlook/blob/d00ac57a865e853dfa8dabc7f13f3ab05675bd24/app/electron/preload/webview/elements/move/stub.ts#L20

<img width="638" alt="Screenshot 2024-10-17 at 6 20 22 PM" src="https://github.com/user-attachments/assets/48ee5ac0-3725-4d7e-b49b-98cc9eec10a1">

**Comment by Ashutoshdas-dev** [comment]
hey @Kitenite assign me this issue under the label

**Comment by Kitenite** [comment]
Go for it @Ashutoshdas-dev

**Comment by drfarrell** [comment]
Hey @Ashutoshdas-dev how's it going so far? Need any help?

**Comment by Ashutoshdas-dev** [comment]
Hey @drfarrell , sorry for the delay. I literally forgot about it due to some university work. I'm currently working on it now and will let you know if I get stuck.

**Comment by drfarrell** [comment]
Closing because this was solved with #649
