### ISSUE TITLE
[feat] Improve the project carousel design

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#599]
The original mockup had a number of features:

![image](https://github.com/user-attachments/assets/2e4ca98b-6882-4f4a-88eb-6eb843ba15cd)

1. The projects that are out-of-focus are smaller and have 60% opacity applied
2. You can see a portion of the top / bottom of the next / previous project in the carousel. The trickiness is that the previews are often different dimensions than another, so you may need to set a fixed gap in the carousel. 

Also, as we look to experiment adding in an acrylic background, it'd be good to fix the hover state overlay on the project card so it doesn't exceed the height of the project. 
<img width="805" alt="image" src="https://github.com/user-attachments/assets/99e8fdf4-7a10-42c2-9412-236b898c50e7">

**Comment by abhiroopc84** [comment]
Can I work on this @drfarrell ?

**Comment by sairiteshdomakuntla** [comment]
hello @drfarrell , can you assign this to me?

**Comment by Kitenite** [comment]
Go for it @abhiroopc84!

**Comment by Kitenite** [comment]
@sairiteshdomakuntla I'll give Abhiroop preference since he was first but are there any other I can assign you instead?

**Comment by drfarrell** [comment]
@sairiteshdomakuntla do you want to take this one on? https://github.com/onlook-dev/onlook/issues/475 #475

**Comment by sairiteshdomakuntla** [comment]
> @sairiteshdomakuntla do you want to take this one on? #475

yes, i think i can work on that
