### ISSUE TITLE
[bug] clicking the right-click menu item of "edit text" doesn't actually activate text editing mode

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#616]
clicking the right-click menu item of "edit text" doesn't actually activate text editing mode. Enter does, but clicking the menu doesn't.

<img width="748" alt="image" src="https://github.com/user-attachments/assets/362f1165-a078-4647-b0a2-d80ab23d9587">

**Comment by Kitenite** [comment]
This seems to work on the canvas but not on the layers

**Comment by aafaris** [comment]
Hi, can I look into this? Please do assign. Thanks!

**Comment by Kitenite** [comment]
Hey @aafaris , go for it. Thank you!

**Comment by Kitenite** [comment]
Fixed
