### ISSUE TITLE
Codebase needs to be commented

### ISSUE THREAD

**Issue by Bicheka** [onlook-dev/onlook#617]
I am new to this project and I was working in another issue but it is really complicated to navigate through the entire codebase trying to figure out how things work when you have never seen the code before and don't know how things work together. I did not find a single comment explaining how things work. It would be really nice if the codebase gets commented for newcomers to get a better understanding.

**Comment by abhiroopc84** [comment]
@drfarrell what do you think about this? I personally could understand most of the code after spending a couple of minutes with it, but I can understand why most people might not be able to figure out how things work together even if they understand individual component code

**Comment by Kitenite** [comment]
Hey @Bicheka, thanks for opening the issue. This is a good topic for discussion. 

I think we could do much better about documenting the codebase. I'm planning to do this more through our [wiki](https://github.com/onlook-dev/onlook/wiki/Architecture) and [YouTube channel](https://www.youtube.com/playlist?list=PLeFyWJaeto-90M99tTL9nP8r-lGbd46Cc). Feel free to join our [Discord](https://discord.gg/hERDfFZCsH) for discussions with me and our other contributors about implementation details.

I subscribe to the idea in Clean Code that comments should be minimized and reserved for when absolutely necessary ([here's a summary](https://medium.com/codex/clean-code-comments-833e11a706dc)). Thus, I hope the code speaks for itself by using readable naming, well-factored function calls and good organization. If you run into code that is difficult to understand, I would highly recommend opening a [help wanted](https://github.com/onlook-dev/onlook/issues/new?assignees=&labels=help+wanted&projects=&template=help_wanted.md&title=%5BHelp%5D+the+title+of+help+wanted+report) issue about it such that it can be improved and refactored. 

I also acknowledge that we need to be better about making the code easier to understand. I am open to being wrong about our approach. What are your thoughts on this?
