### ISSUE TITLE
[feat] Ability to drag the window frame around the canvas

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#619]
Ability for a user to select the top of the browser controls and drag the selected window around the infinite canvas. This is a pre-step leading up to #196 being able to be built as well as #420

**Comment by thvroyal** [comment]
Hi @drfarrell, can I take it?

**Comment by Kitenite** [comment]
@thvroyal go for it!

**Comment by thvroyal** [comment]
Hi @Kitenite and @drfarrell, I just opened a PR to address this issue. Please help me review it. Link to PR: https://github.com/onlook-dev/onlook/pull/715

**Comment by Kitenite** [comment]
Nice it's merged! I had a question in the code but moreso to understand a technique you used @thvroyal

**Comment by thvroyal** [comment]
@Kitenite just commented to explain! Let me know if it’s not clear.

**Comment by Kitenite** [comment]
@thvroyal Yep it makes sense. Thanks for explaining to me :)
