### ISSUE TITLE
[FEAT] New UI v1.0 designs

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#62]
#### Describe the feature
@drfarrell  to add more context.

We have some exciting designs planned for the UI to move away from the current placeholder designs. This is a good task for familiar with the front-end and tailwind. 

TODO: 
1. Implement the design
2. Add design tokens as necessary for scaling up the design system

**Comment by drfarrell** [comment]
[New UI v1.0 #62.pdf](https://github.com/user-attachments/files/16274071/New.UI.v1.0.62.pdf)
Added an annotated design file for the new UI, breaking down the top navigation bar and the left sidepanel.

**Comment by Kitenite** [comment]
Closing this since it's pretty much done. Feel free to reopen or open a separate issue if there are still lingering design changes @drfarrell
