### ISSUE TITLE
[feat] Structure the monorepo with common structure

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#633]
#### Describe the feature

https://lucapette.me/writing/how-to-structure-a-monorepo/?utm_source=atom_feed

Examples:
https://github.com/supabase/supabase
https://github.com/microsoft/vscode
https://github.com/vercel/next.js/

**Comment by hitaspdotnet** [comment]
I'm going for it if assign me.

**Comment by Kitenite** [comment]
Done!
