### ISSUE TITLE
[feat] Lock Responsive Window Dimensions

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#645]
#### Describe the feature
Allow the user to "Lock" the dimensions in place, disabling the ability for them to resize the window. They would do this from the responsive dropdown.

<img width="416" alt="image" src="https://github.com/user-attachments/assets/0de1f00c-0c45-4d68-8b0d-f5f23b6405ea">

This is anticipation of having a "media-queries" feature that may function a bit like this, where it changes the editing mode to only apply properties in that dimension.

![image](https://github.com/user-attachments/assets/0e4bcc4d-73da-4fec-8290-237144a7c0d4)

This is still under design review.

**Comment by abhiroopc84** [comment]
@drfarrell I'd like to work on this

**Comment by drfarrell** [comment]
All you my dude!
