### ISSUE TITLE
[bug] Installer is not signed

### ISSUE THREAD

**Issue by Moccassins** [onlook-dev/onlook#648]
Unfortunately, the installer is not digitally signed. This leads to Windows 11, for example, complaining that this installation package is not trustworthy, which ultimately leads to nothing being installed. You can install it if you explicitly ignore the risk. However, depending on the security guidelines set, this may not be possible.

**Comment by Kitenite** [comment]
Still is still in progress w/ the Microsoft/Azure team

**Comment by Kitenite** [comment]
https://github.com/onlook-dev/onlook/pull/960
