### ISSUE TITLE
[bug] Properties panel close animation is slightly buggy

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#651]
The properties panel elements trail behind in the animation

Some frames: 
<img width="451" alt="Screenshot 2024-10-25 at 2 14 00 PM" src="https://github.com/user-attachments/assets/986e1d59-f078-4848-b8d1-e4deef5a47ad">
<img width="438" alt="Screenshot 2024-10-25 at 2 14 33 PM" src="https://github.com/user-attachments/assets/b55abefa-4eda-4737-89a0-115156b8494c">
<img width="390" alt="image" src="https://github.com/user-attachments/assets/63fac042-bcc1-4cb3-9ba0-8fa2c44a4fd2">

Perhaps we just need to set overflow to hidden for the parent container?

**Comment by PrakharJain1509** [comment]
@drfarrell Is this issue still open to work?

**Comment by PrakharJain1509** [comment]
@drfarrell If its still open, Can I contribute in this?

**Comment by PrakharJain1509** [comment]
@Kitenite @drfarrell Can you help me to just locate where is the code for this styles button. It would be really helpful, Thanks

**Comment by PrakharJain1509** [comment]
@drfarrell @Kitenite I have created a PR resolving this. #654. Please review it and let me know if any changes are required.
