### ISSUE TITLE
[feat] Swap in Light Mode Assets for the onboarding page and the project creation page

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#655]
Need to handle the light / dark mode of these assets robustly. Upload the assets to the src/assets folder and apply them correctly. 

![dunes-create-light](https://github.com/user-attachments/assets/ec375a2f-3bea-4b42-9704-d75b8815b0d7)
![dunes-login-light](https://github.com/user-attachments/assets/c4cb25e8-7491-4dfc-94fd-2a0661e63a56)

**Comment by abhiroopc84** [comment]
@drfarrell I'd like to work on this. The sand dunes in light mode look 🔥.

**Comment by Kitenite** [comment]
Go for it @abhiroopc84 !

**Comment by abhiroopc84** [comment]
@drfarrell this can be closed
