### ISSUE TITLE
[feat] When a new element is drawn in a stack or grid, insert it to the closest reasonable index

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#662]
Currently new elements append to the end of the stack or grid, but it would be expected that the element is dropped-in within the stack or grid at the index closest to where it was drawn.

**Comment by Kitenite** [comment]
This should be somewhat straightforward using existing helpers from drag elements and change get insert location to return an index instead of an append
https://github.com/onlook-dev/onlook/blob/615ea6c92ec55765ca4767ad5e194395750d3873/app/electron/preload/webview/elements/dom/insert.ts#L9-L21

**Comment by sambhavnrana** [comment]
Would like to work on it @drfarrell :)

**Comment by Kitenite** [comment]
Go for it @sambhavnrana
