### ISSUE TITLE
[bug] Navbar visibility issue

### ISSUE THREAD

**Issue by Unnati2603** [onlook-dev/onlook#669]
![image](https://github.com/user-attachments/assets/de23b84a-072c-407e-8b4f-a821b826c19b)
The navbar is not visible. A glassy finish can be added. Can I be assigned the same under the hacktoberfest tag?

**Comment by Kitenite** [comment]
This is a website issue so I can't assign a contributor to it @Unnati2603. But I appreciate the report!
I'd be happy to add the tag to any other issues you'd like to work on

**Comment by Unnati2603** [comment]
> This is a website issue so I can't assign a contributor to it @Unnati2603. But I appreciate the report!
> I'd be happy to add the tag to any other issues you'd like to work on

Ok 👍
