### ISSUE TITLE
[bug] Inserting Div resets text to be center aligned

### ISSUE THREAD

**Issue by winslet** [onlook-dev/onlook#672]
#### Describe the bug

When inserting a new div into the page, text is rest to be center aligned instead of the left aligned chosen previously.

The undo buttons dont undo this change either, they do undo the insertion of the div but the text remains center aligned.

**Comment by Kitenite** [comment]
@winslet , is the expected behavior in this case for text alignment to adhere to the parent's configuration?

**Comment by winslet** [comment]
Hmm I just closed and restarted Onlook and I cant seem to replicate the bug any longer - im going to try and grab you a screencap of the problem.

But yes - when inserting a new div, then I would expect the text to remain with its current settings.

**Comment by winslet** [comment]
Yup definitely can't replicate the problem, must have been a one off. I'll close this issue for now.

**Comment by Kitenite** [comment]
I see. That's weird. Please let me know if it resurfaces :)
