### ISSUE TITLE
[feat] Duplicate the current window into a new Window

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#674]
Ability for a user to create a copy of the current window and it's sizing about 100px to the right of the current window.

- Maintain the same dimensions, position on the page, dimensions, and all attributes of the window. 
- The button to do this with will be a "plus-circle" icon and the tooltop will say "Duplicate Window". This "Plus" button will later be a drop-down menu of creating a "Linked Window" (all scrolls and actions from the parent and child windows will be rendered across both windows) or an "Unlinked Window" (a separate instance / playground of the same window that isn't connected)

<img width="491" alt="image" src="https://github.com/user-attachments/assets/1e8a1657-7734-4199-a71d-4b67845a6bd8">

This is related to #619 and #196

**Comment by Kitenite** [comment]
Aye aye @abhiroopc84
