### ISSUE TITLE
[feat] Further UI improvements to Responsive Windows

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#675]
Continuing on #645, these are a number of UI changes to improve the "responsive" design element in the top browser bar.

- When the dimensions are not set to a device, show the dimensions in the button label. This should update immediately as a user changes the dimensions of their page. Ideally the number is "live" where the user drags the handles, and the number is instantly incremented for every pixel.
<img width="381" alt="image" src="https://github.com/user-attachments/assets/d0efd970-5089-451c-b902-5e7180fbc3e7">

- When the dimensions are set to a device, change the label of the button to that device. 
<img width="420" alt="image" src="https://github.com/user-attachments/assets/56d55f07-ed25-4f35-a04e-f7286e331d56">

- When the dimensions are set to a device AND the lock is enabled, change the label of the button to that device and show the lock.
<img width="514" alt="image" src="https://github.com/user-attachments/assets/e29298a5-4290-4e05-8bd3-70e453b2bc9c">

- Make a little bit of margin / padding of the hover background to closer-match the margin of the right-click menu.
<img width="318" alt="image" src="https://github.com/user-attachments/assets/d09e6fd6-8aab-4361-a3c8-8b37a38d7be8">

**Comment by drfarrell** [comment]
It would be nice to have the numbers animate using something like 

https://x.com/mbarvian/status/1846234563695333605?s=46&t=pd3uh4BnhkMVspxVU9blSQ

https://github.com/barvian/number-flow

**Comment by drfarrell** [comment]
Actually going to pause on this issue for some more updated designs that may make this work less relevant.

**Comment by Kitenite** [comment]
Solved
