### ISSUE TITLE
[feat] Layers panel is buggy

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#702]
Layers are often not representing what is on the canvas. Sometimes it takes a bit for the layers to "Settle" when the app is first loaded in. 

"I couldn't edit divs on Windows. For some reason it's kinda buggy. When I add any divs, it didn't appear in the layers panel."

When a new layer is added, it should be default selected in the layers panel.

**Comment by Kitenite** [comment]
Love it! It's kind of a hairy problem so glad you're jumping on.

This is where the tree is implemented. It builds from an array of layers that's being passed back from the DOM. Let me know as you go through if you have any issues :)

https://github.com/onlook-dev/onlook/blob/980d60a0882c3f561a56c825e995f04ec62ef2bf/apps/studio/src/routes/editor/LayersPanel/LayersTab.tsx#L124-L139

**Comment by happymvp** [comment]
Hello @Kitenite unfortunately this task is too complicated and overwhelmed to work on as open-source contribution. I don't have so much free time. There are many aspects and bugs inside. So I guess it should be carefully reviewed by core team and divided in small clear issues.

**Comment by Kitenite** [comment]
Hey @happymvp , yeah no worries. This is very deep rooted and I'm starting to work on this. Thanks for giving it a shot.
