### ISSUE TITLE
[feat] Right-click to add to AI chat + Hotkey for adding to chat

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#723]
Right-click to add selected element(s) to chat. Remember that a user may be holding SHIFT down and selecting multiple elements. 
<img width="385" alt="image" src="https://github.com/user-attachments/assets/661cbf17-fe19-45f8-98ba-1e99514d3e9e">

Hotkey (CMD+SHIFT+L) that adds the selected element code chunk to the existing chat

Hotkey (CMD+L) that starts a new AI chat with the selected element code chunk.

**Comment by drfarrell** [comment]
Also fits in the family of Right Click actions #683 #206 #520

**Comment by Kitenite** [comment]
This is for the chat functionality which is only available in beta. Standby.

**Comment by Kitenite** [comment]
This is now ready to be picked up now that AI is in main. Should just be a simple tab switch.

**Comment by RaghavGanesh7** [comment]
Hey @drfarrell @Kitenite, Can I take up this task?

**Comment by Kitenite** [comment]
@RaghavGanesh7 go for it!
