### ISSUE TITLE
[FEAT] Right-Click Menu v0

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#73]
So much functionality in an editor can be enabled with a right-click menu. It helps abstract away secondary actions. 

- The right-click menu will be used for both elements on the canvas and in the toolbars of the browser. 
- Right-click actions should also show Hotkeys. If Hotkeys aren't in-production yet, placeholder hotkey labels can be commented-out of the components
- The icons are Radix icons. 
- Please use the custom tailwind styles when implementing these so we keep everything on brand 😄 

![image](https://github.com/user-attachments/assets/46e715af-8d8a-4744-8e55-22183f167d7a)
![image](https://github.com/user-attachments/assets/d7ee810b-7b7d-4664-82d6-2bfc13bf25d1)

**Comment by Kitenite** [comment]
I like it!  Some good options to stub out:
<img width="200" alt="Screenshot 2024-07-18 at 9 36 53 AM" src="https://github.com/user-attachments/assets/488382da-16cb-4532-823b-69962f15d270">

**Comment by Kitenite** [comment]
Assigning @nicklammo

**Comment by Kitenite** [comment]
@nicklammo since you're already working on this, please comment on this issue then I can add you as an assignee

**Comment by nicklammo** [comment]
@Kitenite I gave it a good try anyway

**Comment by Kitenite** [comment]
Nick delivered a fork, will work on adding it to a PR.

**Comment by drfarrell** [comment]
Added in some standard menus for right-clicking on a layer or a component on the canvas. New hotkeys for each feature are bolded and italicized. 

V0

- [ ] Copy: ⌘C
- [ ] Paste here:  ⌘V
- [ ] Cut: ⌘X
- [ ] Duplicate: ⌘D
- [ ] Delete: ⌫
- [ ] Select all: ⌘A
- [ ] Bring to front: ]
- [ ] Send to back: [
- [ ] Add auto layout: ⇧A
- [ ] Show/Hide UI: ⌘.

V1

- [ ] Copy: ⌘C
- [ ] _**Copy/Paste as:**_
- [ ]  - Paste here: ⌘V
- [ ]  _**- Paste styles: ⌥⌘V**_
- [ ] Cut: ⌘X
- [ ] Duplicate: ⌘D
- [ ] Delete: ⌫
- [ ] Bring to front: ]
- [ ] Send to back: [
- [ ] _**Create Div around selection: ⌘G**_
- [ ] _**Undo Div around selection: ⇧⌘G**_
- [ ] Add auto layout: ⇧A
- [ ] Show/Hide UI: ⌘.

V2

- [ ] Copy: ⌘C
- [ ] Copy/Paste as:
- [ ] _**- Copy as SVG: ⇧⌘C**_
- [ ] _**- Copy link to selection: ⌥⌘L**_
- [ ] - Paste here: ⌘V
- [ ] - Paste styles: ⌥⌘V
- [ ] Cut: ⌘X
- [ ] Duplicate: ⌘D
- [ ] Delete: ⌫
- [ ] Bring to front: ]
- [ ] Send to back: [
- [ ] Create Div around selection: ⌘G
- [ ] Undo Div around selection: ⇧⌘G
- [ ] Rename: ⌘R
- [ ] Add auto layout: ⇧A
- [ ] _**Create component: ⌥⌘K**_
- [ ] Show/Hide UI: ⌘.
- [ ] _**Lock/Unlock: ⌥⌘L**_

**Comment by Kitenite** [comment]
We don't have the defined functionalities yet, marking as blocked until further notice
