### ISSUE TITLE
Error Initializing Git Repository

### ISSUE THREAD

**Issue by deltaminimal** [onlook-dev/onlook#756]
When trying to create a new project the following error is displayed:

![image](https://github.com/user-attachments/assets/5bdb8bf2-65ad-433d-880f-f06a7605b733)

**Comment by Kitenite** [comment]
Thanks for reporting @deltaminimal, I will take a look

**Comment by deltaminimal** [comment]
So it seems that the problem was on my end, I didnt have node.js installed on the pc I was trying Onlook, I installed it and ir works now. Perhaps a messege that warns about this when its not installed or a reminder of the requirements would be useful. Thanks and sorry if I wasted your time!

**Comment by Kitenite** [comment]
Hey @deltaminimal, actually this was really useful. Thanks for following up with the issue! 

I had a hard time figuring out why this was happening until you commented. I will keep this open until we get better error messaging :)

**Comment by Kitenite** [comment]
This should no longer be an issue now that we're doing precheck for git and node. Thanks for reporting @deltaminimal
