### ISSUE TITLE
[feat] Right-Click to "View Element Code" should persist as an option

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#759]
"View Element Code" should persist at the top of the right click menu. Right now it only appears if Onlook is detected on the project, which sometimes takes a few seconds.

If it's not enabled, it should be grayed-out. Ideally there's a loading spinner in-place of the icon, but it's jarring to a user when they can't select it or don't know where it is. 

<img width="341" alt="image" src="https://github.com/user-attachments/assets/890af658-f20c-45b8-aaee-36e104c2b870">

**Comment by Kitenite** [comment]
https://github.com/onlook-dev/onlook/pull/947
