### ISSUE TITLE
[feat] In-Toolbar Mini Terminal

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#760]
The terminal would sit on the right side of the toolbar. When a user clicks the button it expands the terminal into a minified view.
<img width="514" alt="image" src="https://github.com/user-attachments/assets/90a41d91-c466-4851-ba03-ddbf5248271a">

Minified terminal view
<img width="707" alt="image" src="https://github.com/user-attachments/assets/0e52d1af-6de3-406c-b712-bbd568a56465">
<img width="852" alt="image" src="https://github.com/user-attachments/assets/e740c094-ad13-44a1-8dd6-9b4395be627f">

The statuses: 
- Red for failed / fatal error + Exclamation triangle icon
- Yellow for errors but still able to run the app + Stop to show the app is running
- Yellow + Play to show you can run the app even if there are errors. Make the outline and text yellow.
- Green + Stop to show the app is running. 
- Green + Play to show the app can run. Just show the regular default button

The buttons on the bottom just insert and run the commands. The goal is to make it so new users to the terminal can learn how to use it through the buttons. 
- Run the App = npm run dev (or whatever command makes the most sense)
- Stop the App = CTRL + C 
- Clear = clear
- Open current directory = open the user's folder in Finder. We'll probably want to add in a "List" (ls) functionality but we'll see what else we need

There are a few steps for this: 
1. Make the Terminal actually work 
2. Make the Terminal UI in the toolbar (Abhiroop used https://www.npmjs.com/package/react-terminal-ui as a quick UI out of the box)
3. Make the UI work with the Terminal
4. Make the Command buttons work

The design doesn't show the entire scope of everything, but let me know if you have questions.

**Comment by drfarrell** [comment]
@Kitenite should we close this out? There are a bunch of smaller improvements we can probably move to other issues.

**Comment by Kitenite** [comment]
Up to you, we can rename it as well

> @Kitenite should we close this out? There are a bunch of smaller improvements we can probably move to other issues.
