### ISSUE TITLE
[bug] Prevent the url bar from shrinking too small

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#795]
#### Describe the bug
<img width="764" alt="Screenshot_2024-11-17_at_9 26 02_PM" src="https://github.com/user-attachments/assets/d5445ff2-80c3-466a-b9e4-a074c4b92158">

**Comment by tabzzz1** [comment]
hey! @Kitenite I think I can try to solve this problem, please give me a chance, thank you!

**Comment by Kitenite** [comment]
For sure, go for it @tabzzz1 !
