### ISSUE TITLE
[feat] Improved AI Chat Scrolling

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#801]
Applying these conditions to our AI chat for the best user experience. 

LLM Scrolljacking Manifesto
1. If the user scrolls to bottom of generated text while still generating, enable auto-scroll
2. Stop auto-scroll if the user manually scrolls up at any point & do not turn it back on until the user manually scrolls to bottom
3. On mobile, stop auto-scroll if the user's finger is touching the screen
4. If you choose to enable auto-scroll by default, stop auto-scrolling when the start of the response gets to the top of the visible window.

Performance tips
1. Do not trigger auto-scroll callback on every token, only set new scroll position (or animate) when height of the container changes.
2. If using React hooks, your state machine will depend on re-renders which can add jank due to latency. Use a class component & class variables to keep track of scroll state independent of renders.

From: https://x.com/mayfer/status/1858698456086282583?s=46&t=pd3uh4BnhkMVspxVU9blSQ 

![image](https://github.com/user-attachments/assets/aedfa232-01d8-4660-9894-e952c7bf73de)

**Comment by tasbi03** [comment]
hey,can you assign me this?

**Comment by Kitenite** [comment]
For sure go for it @tasbi03

**Comment by Kitenite** [comment]
Solved
