### ISSUE TITLE
[feat] Window settings in the sidebar

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#809]
Build the right sidebar for the window that shows up when you have a window selected, but no divs in the window selected. 
![image](https://github.com/user-attachments/assets/311568a2-90d8-4976-8c7a-421dc765d67a)

We don't need the "duplicate" and "delete" functionality just yet so you can just build that UI and hide it. I think we'll probably want to write up a separate PR.

**Comment by abhiroopc84** [comment]
Up for grabs? @drfarrell

**Comment by drfarrell** [comment]
you know it! I'll assign you
