### ISSUE TITLE
[feat] Simplified top-bar controls

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#810]
This is lightly related to #809 

The goal here is to simplify the top-bar to be closer to what Figma has, while creating unique top-bar configurations depending on the state of the project / window. For example...
- Is the project connected to Onlook?
- What mode is the user in? Design or Interact

### 1. Click-and-drag
The area of the top-bar should be click-and-draggable, removing the need for the "drag" icon on the top of the window that currently exists. 

![Export-1732411361891](https://github.com/user-attachments/assets/85c6f248-71f6-4496-a170-029fe2ea81cc)

### 2. Consolidate window controls to a dropdown
Many of the functions we currently have can be consolidated to a dropdown on the far right corner of the page while in Design mode. 

<img width="1512" alt="Annotations" src="https://github.com/user-attachments/assets/d0d21932-6f2f-46ef-8f3a-02592f16fa0f">

### 3. Different controls during Interact mode 

The top bar controls should appear in interact mode according to the directions outlined here: 
<img width="1512" alt="Multiple Windows" src="https://github.com/user-attachments/assets/40cd2949-b01a-4580-b888-d5e2e01a324e">

**Comment by Kitenite** [comment]
@drfarrell this is done?

**Comment by Kitenite** [comment]
This seems done. Pls reopen if not.
