### ISSUE TITLE
[feat] Simplified Window URL 

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#811]
Combined with #810, but...

1. Make the window controls consolidate when the screen size is small, and 
2. When a user double-clicks the url is when they can type the url. Make the url field the full width if it's too small for the user to see what they are typing.

<img width="532" alt="image" src="https://github.com/user-attachments/assets/679a30e8-4f19-4629-9b1f-bc56fcb4a9b6">

**Comment by drfarrell** [comment]
It'd be good to make a minimum window width too of say 280px. I think 300 is the standard, but just to be a little generous, I think 280 would be good.

**Comment by abhiroopc84** [comment]
> It'd be good to make a minimum window width too of say 280px. I think 300 is the standard, but just to be a little generous, I think 280 would be good.

Any minimum height? Or should I let the height be as is?

**Comment by Kitenite** [comment]
This seems done
