### ISSUE TITLE
[FEAT]  How to use it in umi

### ISSUE THREAD

**Issue by shancheng-77** [onlook-dev/onlook#812]
#### Describe the feature
I want to try to use onlook in umi, which is part of my umijs configuration.
![image](https://github.com/user-attachments/assets/a884abef-4287-4d17-b51e-e044a8bf7efe)
However, it was not detected that I used onlook in the application, and the application could not edit the code.
So I want to know the correct configuration method or when cli can support umi.
Thank you very much！

**Comment by Kitenite** [comment]
Hey @shancheng-77, there will soon be a new version where there is no longer a configuration step. This will be released in a few days. https://github.com/onlook-dev/onlook/pull/782

In the meantime, can you verify that the babel plugin is installed in `package.json`? Something like this
```
 "devDependencies": {
    "@onlook/babel-plugin-react": "latest",
  }
```
https://github.com/onlook-dev/onlook/blob/main/demos/babel/package.json#L40

Thank you for your patience :)

**Comment by drfarrell** [comment]
Hey @shancheng-77 try out the latest version of Onlook when you get a chance – there should be an update button that appears after 30 seconds when you start the app up again!

**Comment by shancheng-77** [comment]
> Hey @shancheng-77, there will soon be a new version where there is no longer a configuration step. This will be released in a few days. #782
> 
> In the meantime, can you verify that the babel plugin is installed in `package.json`? Something like this
> 
> ```
>  "devDependencies": {
>     "@onlook/babel-plugin-react": "latest",
>   }
> ```
> 
> https://github.com/onlook-dev/onlook/blob/main/demos/babel/package.json#L40
> 
> Thank you for your patience :)
I'm sorry that I just saw the message. At that time,I carried out this order. ： `npm install -D @onlook/babel-plugin-react`,
So there should be this dependence.

**Comment by shancheng-77** [comment]
> Hey @shancheng-77 try out the latest version of Onlook when you get a chance – there should be an update button that appears after 30 seconds when you start the app up again!

It seems to be okay. good job！
