### ISSUE TITLE
[bug] Resize handlers don't match the size of webview

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#821]
#### Describe the bug

As I reduced the screen size, the screen size adjusted as expected. However, the browser navbar ( URL bar, refresh button, etc.) did not resize accordingly. This left a noticeable gap on the right side of the screen.

![image](https://github.com/user-attachments/assets/ed8ca19f-7a94-4a4a-8db1-208e77f5cac0)

**Comment by abhiroopc84** [comment]
@Kitenite this is fixed in the PR for topbar controls and minimum width for editor
