### ISSUE TITLE
[bug] Side-scrolling when the page has a small width

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#827]
Side-scrolling occurs when the top-bar has too many items and the width of the editor is small.

Perhaps we set a minimum editor width, or hide more items at a smaller screen size.

https://github.com/user-attachments/assets/9e7ec05d-242b-480e-9a23-6ae1bfc50b41

**Comment by Prayag-09** [comment]
Hi, since the issue hasn't been assigned yet, could you please assign it to me? I'd be happy to work on it.

**Comment by Kitenite** [comment]
https://github.com/onlook-dev/onlook/pull/953
