### ISSUE TITLE
[bug] Prevent deleting core elements

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#851]
#### Describe the bug

There's been instances of people playing around and deleting core elements like body tags or core div tag. Then *surprise pikachu face* when the whole page stops working. 

This is a failure of communication on our part. We should add guard rails for core elements.  Some cases may be:

1. body tag
2. top level div tag in a template. 
3. Perhaps anything following a return statement should not be deleted.

See this great work on preventing deleting array elements by @iNerdStack for inspiration https://github.com/onlook-dev/onlook/pull/786

**Comment by iNerdStack** [comment]
@Kitenite 
This could introduce a "lock element" feature. Some elements can be flagged as locked, so they can't be deleted or moved.
We will lock the core elements by default, while the user can toggle lock in the layer panel for other none core elements.
What do you think?

**Comment by Kitenite** [comment]
@iNerdStack , I think it's more so that users don't know what they should not be deleting. Perhaps we can prevent deletion if the element's parent is NOT another jsx element?

**Comment by iNerdStack** [comment]
Oh, thats clearer now. yes that should work

**Comment by drfarrell** [comment]
@Kitenite this was merged in yea? can we close this out?
