### ISSUE TITLE
Check for NVM if exists as Node dependencies (Node.js Runtime not detected)

### ISSUE THREAD

**Issue by whjvenyl** [onlook-dev/onlook#853]
Node.js runtime is installed with nvm, onlook doesn't pick that one up.

![CleanShot 2024-12-06 at 9  41 19@2x](https://github.com/user-attachments/assets/2b9461f3-dda6-486d-9d10-a21bf9dc51d2)
![CleanShot 2024-12-06 at 9  42 54@2x](https://github.com/user-attachments/assets/14a9c320-927f-48d5-89d9-26c26d74ff75)

**Comment by Kitenite** [comment]
Gotcha, will add a check for nvm. Thanks @whjvenyl !

**Comment by Kitenite** [comment]
This should now be fixed by checking the paths for different version managers (next release). Please lmk if there's still an issue @whjvenyl

**Comment by dvnkshl** [comment]
Has this fix shipped? Having the same issue on MacOS, i just download onlook.

**Comment by Kitenite** [comment]
@dvnkshl this should've been fixed. I'm testing it on nvm myself without the issue. Could you share your node version and which node? 

<img width="425" alt="Image" src="https://github.com/user-attachments/assets/5c06d271-d3e6-4cad-8aca-cc48997c1a15" />

**Comment by dvnkshl** [comment]
it works fine for me now!

**Comment by Kitenite** [comment]
Awesome, glad to hear it!
