### ISSUE TITLE
[feat] create project with out git user config

### ISSUE THREAD

**Issue by cqh963852** [onlook-dev/onlook#856]
#### Describe the feature

I am creating a new project on window. 

It show me an error. 

```
Git initialization failed: Error: Command failed: git commit -m "Initial commit" Author identity unknown *** Please tell me who you are. Run git config --global user.email "you@example.com" git config --global user.name "Your Name" to set your account's default identity. Omit --global to set the identity only in this repository. fatal: unable to auto-detect email address (got 'cqh@DESKTOP-3UUOHOC.(none)')
```

can onlook create new project without a git config?

**Comment by Kitenite** [comment]
@cqh963852, 
We'll move away from using git to create the new project in the future. For now, is this a hard blocker for you? 

You could also import any React/Nextjs project instead. This process simply clones this Nextjs template https://github.com/onlook-dev/starter-v1 and import it. So you can clone it or create a new next project https://nextjs.org/learn-pages-router/basics/create-nextjs-app/setup and import it instead. 

Does this help?
