### ISSUE TITLE
[bug] Can not login On Mac

### ISSUE THREAD

**Issue by Speefictor** [onlook-dev/onlook#857]
#### Describe the bug
No matter whether I use GitHub or Google, after I successfully log in in Safari, I cannot jump back to the desktop application and ultimately cannot complete the login

**Comment by Kitenite** [comment]
@Speefictor, 
We've been seeing this lately with Mac, did it ask you to use safe storage? Someone ran into this an it worked on a second try as well

<img width="1728" alt="Screenshot 2024-12-09 at 9 36 58 AM" src="https://github.com/user-attachments/assets/fea5a67c-86ed-4880-bcbf-a9ecdb05b151">

**Comment by Speefictor** [comment]
I have no impression of this information. Now I have successfully logged in. Thank you.
