### ISSUE TITLE
[bug]项目开后不显示内容

### ISSUE THREAD

**Issue by ghostzhang** [onlook-dev/onlook#861]
#### Describe the bug
新建的项目再次打开后显示为空白

![image](https://github.com/user-attachments/assets/b1b05a81-08cc-439f-bba2-37250f4670e0)

**Comment by ghostzhang** [comment]
原因找到了，是退出应用时没有停止服务，直接⌘Q退出后服务没有终止。
再次运行后无法重新启动服务，显示不出内容。

**Comment by Kitenite** [comment]
Hey @ghostzhang , 
Could you click the toggle terminal button and share what it says there?
![image](https://github.com/user-attachments/assets/71faa0d6-e9aa-425f-8a96-62c23782f1c8)

**Comment by ghostzhang** [comment]
> Hey @ghostzhang , Could you click the toggle terminal button and share what it says there? ![image](https://private-user-images.githubusercontent.com/31864905/393860877-71faa0d6-e9aa-425f-8a96-62c23782f1c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTIwMzQsIm5iZiI6MTczMzgxMTczNCwicGF0aCI6Ii8zMTg2NDkwNS8zOTM4NjA4NzctNzFmYWEwZDYtZTlhYS00MjVmLThhOTYtNjJjMjM3ODJmMWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA2MjIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNzhhOThmNDZiMjBkNThhNWZhN2QyNmEwNjkwNzFkMTdkYzIxYTQwOTgzZjNjMmZkM2RiNjA3YWYyZDQ1OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x0bHDAZzt_mj3NwtWfdL08JlVQBAgbA6N-8HFP4xCXk)

![image](https://github.com/user-attachments/assets/c5624ed9-db5f-4248-9019-76f875a5899c)

**Comment by Kitenite** [comment]
@ghostzhang  I see, looks like the thread is not being correctly killed on quit. 
You can kill this process with: `kill $(lsof -t -i:3000)`. I will open a ticket to fix this.

**Comment by Kitenite** [comment]
This is now fixed to handle dangling process on quit. Thank you for reporting :)
