### ISSUE TITLE
[feat] When an element is added to chat, show the element name in chat

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#870]
When a user selects one or multiple elements, use the div name and show a code icon at the top of the chat box so it's obvious that it's been added to the context 

<img width="569" alt="image" src="https://github.com/user-attachments/assets/47ff6024-68ea-43fd-aa3e-6eb0210e66ef">

Specifically, after a user uses the hotkey or they right-click an element and add it to chat

<img width="352" alt="image" src="https://github.com/user-attachments/assets/3c1fa571-ee15-4921-bf24-13eb73929f92">

**Comment by Kitenite** [comment]
Done
