### ISSUE TITLE
[bug] Hotkey to "add an element to a new chat" doesn't work

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#871]
#723 #841 

<img width="411" alt="image" src="https://github.com/user-attachments/assets/5ac84d49-fe24-4c97-8553-4684915750b6">

When I used this hotkey of an element selected, it doesn't start a new chat.

**Comment by drfarrell** [comment]
The right-click to add to chat doesn't work either. 

<img width="411" alt="image" src="https://github.com/user-attachments/assets/82b13e17-9fd8-492c-a5d0-3b934e40acb4" />

**Comment by Kitenite** [comment]
https://github.com/onlook-dev/onlook/pull/951
