### ISSUE TITLE
[bug] Node.js env detection with fnm@Windows

### ISSUE THREAD

**Issue by aranwe** [onlook-dev/onlook#881]
#### Describe the bug
Onlook cannot detect node.js installed via fnm on Windows (which is one of the currently supported methods of installation for node.js) and asks to install standard non-versioned node binaries.

**Comment by aranwe** [comment]
Similar problem to: #853

**Comment by Kitenite** [comment]
This should now be fixed by checking the paths for different version managers (next release). Please lmk if there's still an issue @aranwe
