### ISSUE TITLE
[FEAT] Custom Color Picker

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#89]
We need a custom Color Picker + Variable selector module for Onlook. 

Requirements
* It should use Onlook's custom variables and brand colors
* It should take as little space as possible on the screen
* It should have room for presets to be chosen.

![image](https://github.com/user-attachments/assets/184f7a00-fa66-463f-8bab-0b1632a7af2f)

Some inspiration for what color pickers could look like: 
https://www.tldraw.com/r/IjnaUuT7EdRlaflRWj4Fu?v=-2045,-1060,7478,4112&p=page 

Open for Design suggestions and contributions!

**Comment by Koppeks** [comment]
Hi I would like to help with this, do you need just the design or do you also want a pull request with the code?

**Comment by drfarrell** [comment]
Open to either! Both would be helpful. We already have a base color picker, we just need to wrap it for pre-set variables and such.

<img width="409" alt="Screenshot 2024-07-30 at 7 45 46 PM" src="https://github.com/user-attachments/assets/536de2ff-b05c-4c92-aa41-4325709b86df">

What would you be excited to work on? I can get you a design if you'd like to help implement it. 

This is also similar to this issue https://github.com/onlook-dev/studio/issues/49 if you want to take a look through it and see if there's something there you'd like to work on.

**Comment by Koppeks** [comment]
Does the repo work in Windows? I saw that the only download method was IOS.
If only works on iOS I would be glad to only contribute with design 🦩

**Comment by Kitenite** [comment]
@Koppeks it should work on Windows using the[ local instructions](https://github.com/onlook-dev/studio?tab=readme-ov-file#installation). We just haven't shipped a Windows executable for sake of focus. 

Please let me know if you could not run it.

**Comment by ErrolFernandes** [comment]
![Uploading Frame 3.png…]()

**Comment by ErrolFernandes** [comment]
![Frame 3](https://github.com/user-attachments/assets/fa8c7602-feb3-4ea2-a293-d016125d6923)

**Comment by drfarrell** [comment]
> ![Frame 3](https://private-user-images.githubusercontent.com/83249470/353699725-fa8c7602-feb3-4ea2-a293-d016125d6923.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NjIzMTYsIm5iZiI6MTcyMjQ2MjAxNiwicGF0aCI6Ii84MzI0OTQ3MC8zNTM2OTk3MjUtZmE4Yzc2MDItZmViMy00ZWEyLWEyOTMtZDAxNjEyNWQ2OTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIxNDAxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZmMyYzJhZmZiNzYwMTQzY2JlZmRhNjFhODg0NTMwOGI0NDhlM2M4YTcxYzRhNTk5ODM0ZWUyZmE5YmU1OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r_gGtWwFcdfLmuTZLlmUInfiAMhz_kBp4fiRXynsoDw)

Thanks for putting this together @ErrolFernandes! 

If you want to keep jamming on it, here are some ideas of other things we need. 
- We need to eventually support Gradients like Framer and Figma. Would be great to add those in somewhere. 
- I like how both Figma and Framer let you look over the names of the colors you're looking to choose – it'd be great to see what a list of colors looks like
- Also Figma and Framer have the ability to search for specific colors. Wonder where the best place to put a search bar would be. We use Radix 15px icons if you want to use them as a reference. 
- We'll also need to support HSL, HEX, RGB, etc. colors, so we need a place to swap those modes out.

**Comment by drfarrell** [comment]
<img width="622" alt="image" src="https://github.com/user-attachments/assets/c10dae85-137c-41cc-baf4-0c602ce25166">

A light mockup of what the picker can look like (still will add in gradient and variables and such)

**Comment by drfarrell** [comment]
Here's what I think the v1 design should look like, and there's an even simpler version on the right.
<img width="912" alt="image" src="https://github.com/user-attachments/assets/d52dc09d-fb9c-4ef4-9ad6-bae9d1c00d91">


This is an example showing how the headers should "stick" to the top as the user scrolls through the selection. This will only apply when we have more than one fill type (color, gradient, image, etc.)
![Export-1729268956709](https://github.com/user-attachments/assets/50bac423-395c-448e-a4b4-834a2970c459)

**Comment by hitaspdotnet** [comment]
I'm on it, assign me please if possible.

WIP screen:
![image](https://github.com/user-attachments/assets/04da5cba-ff28-422c-88fd-4f6daa2cb0a2)
