### ISSUE TITLE
[bug] When wrapping divs in a new div, no className attributes are created

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#898]
<img width="493" alt="image" src="https://github.com/user-attachments/assets/123ca103-1947-4317-8151-fb5b777c6584" />

I had two divs that I tried wrapping in another div, but the parent div did not include a classname attribute, so I was unable to assign more tailwind classes to the new parent div.

 
```
<div data-oid="2h-pl05" key="olk-vPLw">
           <div
             className="h-[160px] bg-[#E3F3FF] flex-row block w-[400px]"
             data-oid="z7-5i_h"
             key="olk-lYvO"
           >
             <div
               className="h-[66px] bg-[#1467A5] w-[281px]"
               data-oid="wsec5eo"
               key="olk-KueC"
             ></div>
             <div
               className="w-[121px] h-[66px] bg-[#1467A5]"
               data-oid="30mzgz."
               key="olk-jHl6"
             ></div>
 </div>

```

**Comment by Kitenite** [comment]
Why would you not be able to assign new classnames? The attribute can be created when styling the div

**Comment by Kitenite** [comment]
Seems like if there are no className, we should give you an empty tailwind input and add a property

**Comment by Kitenite** [comment]
https://github.com/onlook-dev/onlook/pull/950
