### ISSUE TITLE
[feat] Implementing Window Controls v1

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#901]
Because we simplified the top bar, we still need a way for the user to choose preset window sizes from the app. https://github.com/onlook-dev/onlook/issues/811

This is a continuation of this issue: https://github.com/onlook-dev/onlook/issues/809 where we actually need the functionality hooked up.

- Device – Allow the user to select a preset device dimension

- Orientation – allow the user to flip the orientation of the width / height in just a click. Also, if the user manually makes the width longer than the height, detect this and change the icon to what is appropriate. 

- Width / Height – Allow the user to specify the width and height of the window in pixels. 
  - You can borrow one of the number input functions that allows the user to use SHIFT+UP/DOWN arrow keys to increment by units of 10, otherwise up / down arrows for increments of 1.
  - Do not let the user input a number that is less than the minimum width / height of the browser windows

- Responsive is something we can hide for now, but it will assign sm:  lg: xl: etc. classes for tailwind values that are written to code from that specific window size. – This will be for V2 because it involves editing how tailwind classes and such are written in code.

- Device settings changes the window setting for whether its light / dark / device mode.

**Comment by abhiroopc84** [comment]
@drfarrell let's get this done!

**Comment by drfarrell** [comment]
Assigned!

**Comment by drfarrell** [comment]
More context (and I'll update this with the list of devices / dimensions

**What would be the device name when I manually adjust the dimensions?**
Device name would just be "Custom" and not available in the list, just a preset we show when the dimensions don't match the device.

**What are the list of devices you want me to include? And should I have a separation for mobile devices, desktop devices, tablet devices in the list?**
I can get you the full list, but I'll borrow it from Figma's list

**The link icon on the width and height input elements is supposed to be a button that locks the aspect ratio, am I right?**
Yup that should lock the aspect ratio, although perhaps we don't include the links for now because I feel like it'll be rare that someone wants that aspect ratio locked as they're manipulating the window. Don't worry about implementing this aspect ratio lock.

**Where will we include the option to lock a preset, like the one I implemented a month back? Is that part of the responsive field?**
The responsive field is the idea behind "locking" the page. I don't think we'll use the same "lock" mechanism, but I'll design a more intuitive solution in the future.

**Comment by Kitenite** [comment]
This seems to be complete
