### ISSUE TITLE
[FEAT] Double-Click to Edit Text in Design Mode

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#91]
Just the typical expected Double-Click interaction to edit text. A single click outside of the text should keep the text selected in the layers panel but turn off "text editing" mode.

Related features
- If data is not static, it could be nice to have a toast or something pop-up that alerts the user that they're about to edit dynamic data, but that's a nice feature to add on-top of the baseline Double-Click to edit. 
- When a user double-clicks, then highlights a certain part of text, then adjusts the style of the highlighted text, it applies the style to just the highlighted selection.

**Comment by Kitenite** [comment]
We would want to edit the text node in the element and write that text node into the AST.

**Comment by spartan-bachdkle** [comment]
H @Kitenite 
I would like to pick up this issue and contribute. Could you please assign it to me to prevent any duplicate work? Thank you!

**Comment by Kitenite** [comment]
Done @spartan-bachdkle

**Comment by Kitenite** [comment]
Hey @spartan-bachdkle, 
Just checking in to see how it's going. Do you need any clarification/support from my side?

**Comment by spartan-bachle** [comment]
> Hey @spartan-bachdkle, 
> 
> Just checking in to see how it's going. Do you need any clarification/support from my side?

Hi @Kitenite i got sick three days before, today i will lock at this. Sorry for that

**Comment by spartan-bachdkle** [comment]
Hey @Kitenite,

After detecting the double-click event in the GestureScreen.tsx file and identifying the text node type, what design should we implement for editing the text?

**Comment by Kitenite** [comment]
@spartan-bachdkle 
No worries, I was really just checking in :)

> what design should we implement for editing the text, inline edit or etc...?

For now, we want to replicate the ability to edit text of Figma that feels like inline. We will add more text editing capabilities later such as bold, italicize, etc. 

I can think of a few ways to get this behavior:
1. Have an input on the overlay that covers the text that replicates the text style, then write it back after
2. Similar to the above but instead makes the text invisible until finish editing
3. Have an explicit text input popup
4. Allow user to edit the text in the page with something like the `content-editable` attribute

I'm a bigger fan of 1 and 2 as it gives us more options to expand the controls later. What are your thoughts or do you have a better option in mind?

For context, Framer does something similar for their input by hiding the text, then add a control mirroring the text's style. 
![Screenshot 2024-08-22 at 9 09 52 AM](https://github.com/user-attachments/assets/8fe089ed-08f7-4715-a4e5-c1a2eb9c7995)

**Comment by drfarrell** [comment]
From a UI/UX side: 

1. While you're editing the text it should feel a lot like a typical text editor.
2. Ideally you should be able to highlight a section of text and apply secondary styles like Bold, Italic, Underline to the highlighted text.
3. To edit the text, select a text box and double-click on it to start editing. When you're done editing, single click outside of the text box to unselect the text box and stop editing. 

![Export-1724333226130](https://github.com/user-attachments/assets/cac422f3-c2e3-465c-812b-643007f342a4)

@spartan-bachdkle does that answer your question?

**Comment by spartan-bachdkle** [comment]
@drfarrell @Kitenite understood. Inline edit is the best choice.

**Comment by spartan-bachdkle** [comment]
@Kitenite I'm working on this. Trying to get element by `DATA-ONLOOK-ID` attribute, add inline edit on overlay

**Comment by Kitenite** [comment]
Awesome! If you'd like to split the text editing functionality and write-to-code into multiple PRs that's ok too

This is an example of write-to-code for insertion: https://github.com/onlook-dev/onlook/pull/168/files
