### ISSUE TITLE
[bug] Flexbox disappears

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#926]
#### Describe the bug

After having AI generate some code and applying flexbox, the controls disappear. When I try to unapply it or select a different layer, the UI bugs out.

<img width="1135" alt="image" src="https://github.com/user-attachments/assets/f17ee75c-f1f2-4a71-9fda-2cc965288295" />
<img width="755" alt="image" src="https://github.com/user-attachments/assets/0c334bb2-95b3-4221-80e8-b82fbd6e77b9" />

https://github.com/user-attachments/assets/8d37bee2-fe8a-487b-b340-a1649f55eb49

**Comment by Kitenite** [comment]
This should now be solved. Please reopen if not.
